const mongoose = require('mongoose');
require('dotenv').config();
mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    const db = mongoose.connection.db;
    await db.collection('cursos').deleteOne({ nivel: 'C2' });
    await db.collection('cursos').insertOne({
      nivel: 'C2',
      temas: [
        { id: 'mastery_vocabulary', titulo: 'Vocabulario de maestria', icono: '👑',
          vocabulario: [
            {en:'Perspicacious',es:'Perspicaz'},{en:'Obfuscate',es:'Ofuscar'},{en:'Ephemeral',es:'Efimero'},
            {en:'Mellifluous',es:'Melodioso'},{en:'Sycophant',es:'Adulador'},{en:'Vociferous',es:'Vociferante'},
            {en:'Labyrinthine',es:'Laberintico'},{en:'Recondite',es:'Arcano / Oscuro'},{en:'Loquacious',es:'Locuaz'},
            {en:'Sagacious',es:'Sagaz'},{en:'Perfidious',es:'Perfido'},{en:'Magnanimous',es:'Magnifico / Generoso'},
          ]},
        { id: 'subtle_nuances', titulo: 'Matices y sutilezas', icono: '🎭',
          vocabulario: [
            {en:'Imply vs Infer',es:'Implicar vs Inferir'},{en:'Affect vs Effect',es:'Afectar vs Efecto'},
            {en:'Comprise vs Compose',es:'Comprender vs Componer'},{en:'Disinterested vs Uninterested',es:'Imparcial vs Sin interes'},
            {en:'Continual vs Continuous',es:'Intermitente vs Continuo'},{en:'Farther vs Further',es:'Mas lejos vs Ademas'},
            {en:'Lay vs Lie',es:'Poner vs Yacer'},{en:'Principal vs Principle',es:'Principal vs Principio'},
            {en:'Literally vs Figuratively',es:'Literalmente vs Figurativamente'},{en:'Deprecate vs Depreciate',es:'Desaprobar vs Depreciar'},
            {en:'Elicit vs Illicit',es:'Obtener vs Ilicito'},{en:'Flaunt vs Flout',es:'Ostentar vs Ignorar'},
          ]},
        { id: 'advanced_rhetoric', titulo: 'Retorica y persuasion C2', icono: '⚡',
          vocabulario: [
            {en:'Ethos',es:'Credibilidad del orador'},{en:'Pathos',es:'Apelacion a las emociones'},
            {en:'Logos',es:'Apelacion a la logica'},{en:'Anaphora',es:'Anafora'},
            {en:'Chiasmus',es:'Quiasmo'},{en:'Litotes',es:'Litote'},
            {en:'Synecdoche',es:'Sinecdoque'},{en:'Periphrasis',es:'Perifrasis'},
            {en:'Antithesis',es:'Antitesis'},{en:'Epistrophe',es:'Epifora'},
            {en:'Understatement',es:'Eufemismo sutil'},{en:'Circumlocution',es:'Circunloquio'},
          ]},
        { id: 'complex_conditionals', titulo: 'Condicionales complejos C2', icono: '🔀',
          vocabulario: [
            {en:'Were it not for the fact that',es:'Si no fuera por el hecho de que'},
            {en:'Had circumstances been different',es:'Si las circunstancias hubieran sido diferentes'},
            {en:'Should the need arise',es:'Si surgiera la necesidad'},
            {en:'But for your intervention',es:'De no ser por tu intervencion'},
            {en:'Supposing that were possible',es:'Suponiendo que eso fuera posible'},
            {en:'Given that this is the case',es:'Dado que este es el caso'},
            {en:'In the event that',es:'En el caso de que'},{en:'On the assumption that',es:'Bajo el supuesto de que'},
            {en:'Provided the conditions are met',es:'Siempre que se cumplan las condiciones'},
            {en:'Only if all parties agree',es:'Solo si todas las partes estan de acuerdo'},
            {en:'Under no circumstances would',es:'Bajo ninguna circunstancia'},
            {en:'Not until much later did',es:'No fue hasta mucho despues que'},
          ]},
        { id: 'native_expressions', titulo: 'Expresiones de hablante nativo', icono: '🇺🇸',
          vocabulario: [
            {en:'That is neither here nor there',es:'Eso no viene al caso'},{en:'By the same token',es:'Del mismo modo'},
            {en:'For all intents and purposes',es:'A todos los efectos'},{en:'In the grand scheme of things',es:'En el gran esquema de las cosas'},
            {en:'Touch and go',es:'Muy incierto'},{en:'A far cry from',es:'Muy diferente de'},
            {en:'Leave no stone unturned',es:'No dejar piedra sin mover'},{en:'The jury is still out',es:'Aun no hay veredicto'},
            {en:'A double-edged sword',es:'Un arma de doble filo'},{en:'On borrowed time',es:'Vivir de prestado'},
            {en:'Draw the line',es:'Poner un limite'},{en:'Move the goalposts',es:'Cambiar las reglas del juego'},
          ]},
        { id: 'advanced_connectors', titulo: 'Conectores de nivel nativo', icono: '🔗',
          vocabulario: [
            {en:'Insofar as',es:'En la medida en que'},{en:'Inasmuch as',es:'Dado que / En tanto que'},
            {en:'By virtue of',es:'En virtud de'},{en:'In lieu of',es:'En lugar de'},
            {en:'With a view to',es:'Con miras a'},{en:'In so far as',es:'En cuanto a'},
            {en:'To the extent that',es:'En la medida en que'},{en:'Vis-a-vis',es:'En relacion con'},
            {en:'De facto',es:'De hecho'},{en:'Inter alia',es:'Entre otras cosas'},
            {en:'Mutatis mutandis',es:'Cambiando lo que se deba cambiar'},{en:'A priori',es:'A priori'},
          ]},
        { id: 'discourse_mastery', titulo: 'Dominio del discurso', icono: '🎙️',
          vocabulario: [
            {en:'It stands to reason that',es:'Es logico que'},{en:'One cannot help but notice',es:'No se puede evitar notar'},
            {en:'It begs the question',es:'Surge la pregunta'},{en:'Without loss of generality',es:'Sin perder generalidad'},
            {en:'All things considered',es:'Considerando todo'},{en:'It is axiomatic that',es:'Es axiomatico que'},
            {en:'By no stretch of the imagination',es:'De ninguna manera'},{en:'At the risk of oversimplifying',es:'A riesgo de simplificar'},
            {en:'The crux of the matter',es:'El punto clave del asunto'},{en:'To put it in perspective',es:'Para dimensionarlo'},
            {en:'It merits serious consideration',es:'Merece seria consideracion'},{en:'This cannot be overstated',es:'Esto no se puede exagerar'},
          ]},
        { id: 'precision_language', titulo: 'Lenguaje de precision', icono: '🎯',
          vocabulario: [
            {en:'Approximately vs Roughly',es:'Aproximadamente vs Aproximadamente (informal)'},{en:'Significant vs Considerable',es:'Significativo vs Considerable'},
            {en:'Crucial vs Critical',es:'Crucial vs Critico'},{en:'Apparent vs Evident',es:'Aparente vs Evidente'},
            {en:'Adequate vs Sufficient',es:'Adecuado vs Suficiente'},{en:'Modify vs Alter',es:'Modificar vs Alterar'},
            {en:'Examine vs Scrutinize',es:'Examinar vs Escudriñar'},{en:'Decline vs Deteriorate',es:'Declinar vs Deteriorar'},
            {en:'Obtain vs Acquire',es:'Obtener vs Adquirir'},{en:'Indicate vs Demonstrate',es:'Indicar vs Demostrar'},
            {en:'Assist vs Facilitate',es:'Asistir vs Facilitar'},{en:'Require vs Necessitate',es:'Requerir vs Hacer necesario'},
          ]},
        { id: 'professional_mastery', titulo: 'Dominio profesional', icono: '💎',
          vocabulario: [
            {en:'Value proposition',es:'Propuesta de valor'},{en:'Paradigm shift',es:'Cambio de paradigma'},
            {en:'Core competency',es:'Competencia esencial'},{en:'Synergy',es:'Sinergia'},
            {en:'Disruptive innovation',es:'Innovacion disruptiva'},{en:'Thought leadership',es:'Liderazgo de opinion'},
            {en:'Strategic alignment',es:'Alineacion estrategica'},{en:'Change management',es:'Gestion del cambio'},
            {en:'Agile methodology',es:'Metodologia agil'},{en:'Scalability',es:'Escalabilidad'},
            {en:'Value chain',es:'Cadena de valor'},{en:'Competitive advantage',es:'Ventaja competitiva'},
          ]},
        { id: 'cultural_mastery', titulo: 'Dominio cultural nativo', icono: '🌟',
          vocabulario: [
            {en:'Catch-22',es:'Situacion sin salida'},{en:'Kafkaesque',es:'Absurdo y burocrático'},
            {en:'Pyrrhic victory',es:'Victoria pirrica'},{en:'Machiavellian',es:'Maquiavelico'},
            {en:'Herculean task',es:'Tarea herculea'},{en:'Sisyphean',es:'Sisifeo / Imposible'},
            {en:'Orwellian',es:'Orwelliano / Totalitario'},{en:'Quixotic',es:'Quijotesco / Idealista'},
            {en:'Promethean',es:'Prometeo / Audaz'},{en:'Draconian',es:'Draconiano / Severo'},
            {en:'Platonic',es:'Platonico'},{en:'Narcissistic',es:'Narcisista'},
          ]},
        { id: 'spontaneous_speech', titulo: 'Habla espontanea y natural', icono: '💬',
          vocabulario: [
            {en:'To be honest with you',es:'Para ser honesto contigo'},{en:'If you ask me',es:'Si me preguntas'},
            {en:'At the end of the day',es:'Al final del dia'},{en:'Come to think of it',es:'Pensandolo bien'},
            {en:'As a matter of fact',es:'De hecho'},{en:'Off the top of my head',es:'De improviso'},
            {en:'For what it is worth',es:'Por lo que vale'},{en:'Between you and me',es:'Entre tu y yo'},
            {en:'If anything',es:'Si acaso'},{en:'Having said that',es:'Dicho esto'},
            {en:'Mind you',es:'Eso si'},{en:'Come to that',es:'Ya que estamos'},
          ]},
        { id: 'grammar_c2', titulo: 'Gramatica C2 — dominio total', icono: '🏆',
          vocabulario: [
            {en:'Absolute construction',es:'Construccion absoluta'},{en:'Dangling modifier',es:'Modificador colgante'},
            {en:'Appositive phrase',es:'Frase apositiva'},{en:'Gerund as subject',es:'Gerundio como sujeto'},
            {en:'Inverted conditional',es:'Condicional invertido'},{en:'Extraposition',es:'Extraposicion'},
            {en:'Cataphoric reference',es:'Referencia catáforica'},{en:'Anaphoric reference',es:'Referencia anaforica'},
            {en:'Garden path sentence',es:'Oracion de interpretacion erronea'},{en:'Structural ambiguity',es:'Ambiguedad estructural'},
            {en:'Zero article usage',es:'Uso del articulo cero'},{en:'Aspect vs Tense',es:'Aspecto vs Tiempo verbal'},
          ]},
        { id: 'humor_wordplay', titulo: 'Humor y juegos de palabras', icono: '😏',
          vocabulario: [
            {en:'Pun',es:'Juego de palabras'},{en:'Wit',es:'Ingenio'},
            {en:'Sarcasm',es:'Sarcasmo'},{en:'Dry humor',es:'Humor seco'},
            {en:'Tongue-in-cheek',es:'En tono de broma'},{en:'Deadpan',es:'Sin expresion (humor)'},
            {en:'Punchline',es:'Remate del chiste'},{en:'Innuendo',es:'Insinuacion'},
            {en:'Self-deprecating',es:'Autocritico (humor)'},{en:'Slapstick',es:'Humor fisico'},
            {en:'One-liner',es:'Chiste de una linea'},{en:'Banter',es:'Bromas amistosas'},
            {en:'To crack a joke',es:'Contar un chiste'},{en:'To take a jab at',es:'Lanzar una pulla a'},
          ]},
        { id: 'proverbs', titulo: 'Proverbios y refranes', icono: '📜',
          vocabulario: [
            {en:'A stitch in time saves nine',es:'Mas vale prevenir que lamentar'},
            {en:'Don’t count your chickens before they hatch',es:'No cantes victoria antes de tiempo'},
            {en:'The early bird catches the worm',es:'Al que madruga Dios lo ayuda'},
            {en:'Birds of a feather flock together',es:'Dios los cria y ellos se juntan'},
            {en:'Actions speak louder than words',es:'Los hechos valen mas que las palabras'},
            {en:'When in Rome, do as the Romans do',es:'Donde fueres, haz lo que vieres'},
            {en:'The grass is always greener on the other side',es:'El pasto siempre parece mas verde al otro lado'},
            {en:'Don’t put all your eggs in one basket',es:'No pongas todos los huevos en una canasta'},
            {en:'Every cloud has a silver lining',es:'No hay mal que por bien no venga'},
            {en:'You can’t judge a book by its cover',es:'No juzgues un libro por su portada'},
            {en:'Better late than never',es:'Mas vale tarde que nunca'},
            {en:'Practice makes perfect',es:'La practica hace al maestro'},
          ]},
        { id: 'legal_english', titulo: 'Ingles legal y burocratico', icono: '⚖️',
          vocabulario: [
            {en:'Hereinafter',es:'En adelante (legal)'},{en:'Notwithstanding',es:'No obstante (legal)'},
            {en:'To indemnify',es:'Indemnizar'},{en:'Null and void',es:'Nulo y sin efecto'},
            {en:'Breach of contract',es:'Incumplimiento de contrato'},{en:'Liability',es:'Responsabilidad legal'},
            {en:'Disclosure',es:'Divulgacion'},{en:'Confidentiality clause',es:'Clausula de confidencialidad'},
            {en:'Binding agreement',es:'Acuerdo vinculante'},{en:'To waive rights',es:'Renunciar a derechos'},
            {en:'Terms and conditions',es:'Terminos y condiciones'},{en:'In witness whereof',es:'En fe de lo cual'},
            {en:'Force majeure',es:'Fuerza mayor'},{en:'Due process',es:'Debido proceso'},
          ]},
        { id: 'literary_language', titulo: 'Lenguaje literario', icono: '🖋️',
          vocabulario: [
            {en:'Whence',es:'De donde (literario)'},{en:'Thither',es:'Hacia alla (arcaico)'},
            {en:'Betwixt',es:'Entre (arcaico)'},{en:'Woe',es:'Afliccion / Desdicha'},
            {en:'Hark',es:'Escucha (arcaico)'},{en:'Forlorn',es:'Desamparado'},
            {en:'Resplendent',es:'Resplandeciente'},{en:'Halcyon days',es:'Dias felices del pasado'},
            {en:'Gossamer',es:'Sutil / Etereo'},{en:'Lament',es:'Lamento'},
            {en:'Reverie',es:'Ensonacion'},{en:'Sublime',es:'Sublime'},
            {en:'Evanescent',es:'Evanescente'},{en:'Yonder',es:'Alla a lo lejos (arcaico)'},
          ]},
        { id: 'regional_english', titulo: 'Ingles britanico vs americano', icono: '🗺️',
          vocabulario: [
            {en:'Lift (UK) / Elevator (US)',es:'Ascensor'},
            {en:'Flat (UK) / Apartment (US)',es:'Apartamento'},
            {en:'Queue (UK) / Line (US)',es:'Fila'},
            {en:'Lorry (UK) / Truck (US)',es:'Camion'},
            {en:'Holiday (UK) / Vacation (US)',es:'Vacaciones'},
            {en:'Rubbish (UK) / Trash (US)',es:'Basura'},
            {en:'Biscuit (UK) / Cookie (US)',es:'Galleta'},
            {en:'Petrol (UK) / Gas (US)',es:'Gasolina'},
            {en:'Autumn (UK) / Fall (US)',es:'Otono'},
            {en:'Bloke (UK) / Guy (US)',es:'Tipo / Hombre'},
            {en:'Y’all (US South)',es:'Ustedes (sur de EE.UU.)'},
            {en:'Reckon',es:'Suponer / Creer (coloquial)'},
            {en:'Cheers (UK)',es:'Gracias / Salud (britanico)'},
            {en:'Fortnight (UK)',es:'Quincena / Dos semanas'},
          ]},
        { id: 'binomials', titulo: 'Binomios nativos', icono: '👥',
          vocabulario: [
            {en:'Odds and ends',es:'Cosas sueltas'},{en:'By and large',es:'En general'},
            {en:'Safe and sound',es:'Sano y salvo'},{en:'Sick and tired',es:'Harto'},
            {en:'Back and forth',es:'De un lado a otro'},{en:'Pros and cons',es:'Pros y contras'},
            {en:'Ups and downs',es:'Altibajos'},{en:'Loud and clear',es:'Alto y claro'},
            {en:'Short and sweet',es:'Corto y conciso'},{en:'Wear and tear',es:'Desgaste'},
            {en:'Give and take',es:'Toma y daca / Ceder mutuamente'},{en:'Now and then',es:'De vez en cuando'},
            {en:'First and foremost',es:'Ante todo'},{en:'Peace and quiet',es:'Paz y tranquilidad'},
          ]},
        { id: 'false_friends', titulo: 'Falsos amigos EN-ES', icono: '⚠️',
          vocabulario: [
            {en:'Actually (en realidad)',es:'NO es "actualmente"'},
            {en:'Embarrassed (avergonzado)',es:'NO es "embarazada"'},
            {en:'Library (biblioteca)',es:'NO es "libreria"'},
            {en:'To assist (ayudar)',es:'NO es "asistir a un evento"'},
            {en:'Sensible (sensato)',es:'NO es "sensible"'},
            {en:'To realize (darse cuenta)',es:'NO es "realizar"'},
            {en:'Carpet (alfombra)',es:'NO es "carpeta"'},
            {en:'Exit (salida)',es:'NO es "exito"'},
            {en:'To attend (asistir)',es:'NO es "atender"'},
            {en:'Constipated (estrenido)',es:'NO es "constipado"'},
            {en:'Fabric (tela)',es:'NO es "fabrica"'},
            {en:'To introduce (presentar)',es:'NO es "introducir"'},
            {en:'Lecture (conferencia)',es:'NO es "lectura"'},
            {en:'Rope (cuerda)',es:'NO es "ropa"'},
          ]},
        { id: 'phrasal_c2', titulo: 'Phrasal verbs de 3 partes', icono: '⛓️',
          vocabulario: [
            {en:'Get around to',es:'Encontrar tiempo para'},{en:'Come down with',es:'Enfermarse de'},
            {en:'Look up to',es:'Admirar'},{en:'Zero in on',es:'Enfocarse en'},
            {en:'Put up with',es:'Tolerar'},{en:'Run up against',es:'Toparse con (problemas)'},
            {en:'Get out of',es:'Librarse de'},{en:'Look out for',es:'Estar atento a'},
            {en:'Come up against',es:'Enfrentarse a'},{en:'Live up to',es:'Estar a la altura de'},
            {en:'Cut down on',es:'Reducir el consumo de'},{en:'Keep up with',es:'Mantenerse al dia con'},
            {en:'Boil down to',es:'Reducirse a'},{en:'Walk out on',es:'Abandonar a'},
          ]},
        { id: 'pronunciation_mastery', titulo: 'Pronunciacion dificil', icono: '🗣️',
          vocabulario: [
            {en:'Colonel',es:'Coronel (se pronuncia "kernel")'},
            {en:'Queue',es:'Fila (se pronuncia "kiu")'},
            {en:'Squirrel',es:'Ardilla'},
            {en:'Thorough',es:'Minucioso'},
            {en:'Sixth',es:'Sexto'},
            {en:'Rural',es:'Rural'},
            {en:'Choir',es:'Coro (se pronuncia "kuaier")'},
            {en:'Anemone',es:'Anemona'},
            {en:'Worcestershire',es:'Salsa inglesa (se pronuncia "wuster-sher")'},
            {en:'Drought',es:'Sequia (se pronuncia "draut")'},
            {en:'Recipe',es:'Receta (se pronuncia "re-si-pi")'},
            {en:'Vegetable',es:'Verdura (3 silabas: "vech-ta-bol")'},
            {en:'Comfortable',es:'Comodo (3 silabas: "komf-ta-bol")'},
            {en:'Phenomenon',es:'Fenomeno'},
          ]},
      ]
    });
    console.log('✅ Seed C2 completo — 21 temas');
    mongoose.disconnect();
  }).catch(e => { console.error(e.message); process.exit(1); });