const mongoose = require('mongoose');
require('dotenv').config();
mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    const db = mongoose.connection.db;
    await db.collection('cursos').deleteOne({ nivel: 'C1' });
    await db.collection('cursos').insertOne({
      nivel: 'C1',
      temas: [
        { id: 'academic_writing', titulo: 'Escritura academica', icono: '📄',
          vocabulario: [
            {en:'Empirical',es:'Empirico'},{en:'Methodology',es:'Metodologia'},{en:'Paradigm',es:'Paradigma'},
            {en:'Dissertation',es:'Disertacion'},{en:'Peer-reviewed',es:'Revisado por pares'},{en:'Citation',es:'Cita'},
            {en:'Plagiarism',es:'Plagio'},{en:'Abstract',es:'Resumen ejecutivo'},{en:'Footnote',es:'Nota al pie'},
            {en:'Bibliography',es:'Bibliografia'},{en:'Quantitative',es:'Cuantitativo'},{en:'Qualitative',es:'Cualitativo'},
          ]},
        { id: 'advanced_idioms', titulo: 'Expresiones avanzadas', icono: '💡',
          vocabulario: [
            {en:'Bite off more than you can chew',es:'Abarcar mas de lo que puedes'},{en:'The ball is in your court',es:'La decision es tuya'},
            {en:'Bury the hatchet',es:'Hacer las paces'},{en:'The tip of the iceberg',es:'La punta del iceberg'},
            {en:'Throw in the towel',es:'Rendirse'},{en:'Beat around the bush',es:'Andar con rodeos'},
            {en:'Get the ball rolling',es:'Poner las cosas en marcha'},{en:'Burn the midnight oil',es:'Trabajar hasta tarde'},
            {en:'Hit the ground running',es:'Comenzar con fuerza'},{en:'Once in a blue moon',es:'Muy de vez en cuando'},
            {en:'Sit on the fence',es:'No tomar partido'},{en:'The writing is on the wall',es:'El final esta cerca'},
          ]},
        { id: 'philosophy', titulo: 'Filosofia y etica', icono: '🤔',
          vocabulario: [
            {en:'Ethics',es:'Etica'},{en:'Morality',es:'Moralidad'},{en:'Epistemology',es:'Epistemologia'},
            {en:'Ontology',es:'Ontologia'},{en:'Determinism',es:'Determinismo'},{en:'Relativism',es:'Relativismo'},
            {en:'Pragmatism',es:'Pragmatismo'},{en:'Consciousness',es:'Consciencia'},{en:'Virtue',es:'Virtud'},
            {en:'Dilemma',es:'Dilema'},{en:'Paradox',es:'Paradoja'},{en:'Transcendence',es:'Trascendencia'},
          ]},
        { id: 'advanced_grammar', titulo: 'Gramatica avanzada C1', icono: '✏️',
          vocabulario: [
            {en:'Inversion for emphasis',es:'Inversion para enfasis'},{en:'Cleft sentences',es:'Oraciones escindidas'},
            {en:'Subjunctive mood',es:'Modo subjuntivo'},{en:'Ellipsis',es:'Elipsis'},
            {en:'Nominalization',es:'Nominalizacion'},{en:'Hedging language',es:'Lenguaje atenuador'},
            {en:'Mixed conditionals',es:'Condicionales mixtos'},{en:'Fronting',es:'Posicion frontal'},
            {en:'Discourse markers',es:'Marcadores del discurso'},{en:'Appositives',es:'Aposiciones'},
            {en:'Reduced relative clauses',es:'Clausulas de relativo reducidas'},{en:'Participle clauses',es:'Clausulas de participio'},
          ]},
        { id: 'negotiation', titulo: 'Negociacion y persuasion', icono: '🤝',
          vocabulario: [
            {en:'Concession',es:'Concesion'},{en:'Compromise',es:'Compromiso'},{en:'Leverage',es:'Influencia'},
            {en:'Mediator',es:'Mediador'},{en:'Arbitration',es:'Arbitraje'},{en:'Deadlock',es:'Punto muerto'},
            {en:'Mutual benefit',es:'Beneficio mutuo'},{en:'Win-win',es:'Ganar-ganar'},{en:'Bottom line',es:'Minimo aceptable'},
            {en:'Stipulation',es:'Estipulacion'},{en:'Clause',es:'Clausula'},{en:'Ratify',es:'Ratificar'},
          ]},
        { id: 'media_criticism', titulo: 'Critica mediatica', icono: '📺',
          vocabulario: [
            {en:'Propaganda',es:'Propaganda'},{en:'Censorship',es:'Censura'},{en:'Objectivity',es:'Objetividad'},
            {en:'Sensationalism',es:'Sensacionalismo'},{en:'Framing',es:'Encuadre informativo'},{en:'Agenda setting',es:'Establecimiento de agenda'},
            {en:'Spin',es:'Manipulacion informativa'},{en:'Whistleblower',es:'Informante'},{en:'Transparency',es:'Transparencia'},
            {en:'Accountability',es:'Responsabilidad publica'},{en:'Disinformation',es:'Desinformacion'},{en:'Deepfake',es:'Contenido manipulado digitalmente'},
          ]},
        { id: 'social_issues', titulo: 'Problemas sociales', icono: '🌍',
          vocabulario: [
            {en:'Discrimination',es:'Discriminacion'},{en:'Inequality',es:'Desigualdad'},{en:'Marginalization',es:'Marginalizacion'},
            {en:'Systemic',es:'Sistemico'},{en:'Privilege',es:'Privilegio'},{en:'Inclusion',es:'Inclusion'},
            {en:'Advocacy',es:'Abogacia'},{en:'Grassroots',es:'De base popular'},{en:'Activism',es:'Activismo'},
            {en:'Reform',es:'Reforma'},{en:'Policy',es:'Politica publica'},{en:'Empowerment',es:'Empoderamiento'},
          ]},
        { id: 'advanced_vocabulary', titulo: 'Vocabulario C1 preciso', icono: '📖',
          vocabulario: [
            {en:'Ambivalent',es:'Ambivalente'},{en:'Compelling',es:'Convincente'},{en:'Contentious',es:'Controvertido'},
            {en:'Detrimental',es:'Perjudicial'},{en:'Elusive',es:'Esquivo'},{en:'Formidable',es:'Formidable'},
            {en:'Inherent',es:'Inherente'},{en:'Nuanced',es:'Matizado'},{en:'Proliferate',es:'Proliferar'},
            {en:'Scrutiny',es:'Escrutinio'},{en:'Undermine',es:'Socavar'},{en:'Unprecedented',es:'Sin precedentes'},
          ]},
        { id: 'presentations', titulo: 'Presentaciones profesionales', icono: '🎯',
          vocabulario: [
            {en:'I would like to draw your attention to',es:'Quisiera llamar su atencion a'},{en:'As previously mentioned',es:'Como se menciono anteriormente'},
            {en:'To summarize the key points',es:'Para resumir los puntos clave'},{en:'This brings me to my next point',es:'Esto me lleva a mi siguiente punto'},
            {en:'Let me elaborate on that',es:'Permitanme profundizar en eso'},{en:'To put it another way',es:'Dicho de otra manera'},
            {en:'The data clearly shows',es:'Los datos muestran claramente'},{en:'It is worth noting that',es:'Vale la pena señalar que'},
            {en:'Moving on to',es:'Pasando a'},{en:'In light of this',es:'A la luz de esto'},
            {en:'The implications are',es:'Las implicaciones son'},{en:'To wrap up',es:'Para concluir'},
          ]},
        { id: 'literature_analysis', titulo: 'Analisis literario', icono: '📚',
          vocabulario: [
            {en:'Allegory',es:'Alegoria'},{en:'Foreshadowing',es:'Presagio literario'},{en:'Motif',es:'Motivo literario'},
            {en:'Connotation',es:'Connotacion'},{en:'Denotation',es:'Denotacion'},{en:'Juxtaposition',es:'Yuxtaposicion'},
            {en:'Hyperbole',es:'Hiperbole'},{en:'Oxymoron',es:'Oxiomoron'},{en:'Allusion',es:'Alusion'},
            {en:'Ambiguity',es:'Ambiguedad'},{en:'Tone',es:'Tono literario'},{en:'Perspective',es:'Perspectiva narrativa'},
          ]},
        { id: 'intercultural', titulo: 'Comunicacion intercultural', icono: '🌐',
          vocabulario: [
            {en:'Cultural sensitivity',es:'Sensibilidad cultural'},{en:'Etiquette',es:'Protocolo'},{en:'Taboo',es:'Tabu'},
            {en:'Stereotype',es:'Estereotipo'},{en:'Assimilation',es:'Asimilacion'},{en:'Multiculturalism',es:'Multiculturalismo'},
            {en:'Xenophobia',es:'Xenofobia'},{en:'Cultural norm',es:'Norma cultural'},{en:'Code-switching',es:'Cambio de codigo'},
            {en:'Subculture',es:'Subcultura'},{en:'Identity',es:'Identidad'},{en:'Acculturation',es:'Aculturacion'},
          ]},
        { id: 'advanced_discourse', titulo: 'Discurso avanzado', icono: '🗣️',
          vocabulario: [
            {en:'Rhetoric',es:'Retorica'},{en:'Oratory',es:'Oratoria'},{en:'Coherence',es:'Coherencia'},
            {en:'Cohesion',es:'Cohesion'},{en:'Register',es:'Registro linguistico'},{en:'Pragmatics',es:'Pragmatica'},
            {en:'Intonation',es:'Entonacion'},{en:'Articulation',es:'Articulacion'},{en:'Fluency',es:'Fluidez'},
            {en:'Precision',es:'Precision'},{en:'Eloquence',es:'Elocuencia'},{en:'Brevity',es:'Brevedad'},
          ]},
        { id: 'collocations_c1', titulo: 'Colocaciones avanzadas', icono: '🧩',
          vocabulario: [
            {en:'Wreak havoc',es:'Causar estragos'},{en:'Pose a threat',es:'Representar una amenaza'},
            {en:'Harbor doubts',es:'Albergar dudas'},{en:'Exert pressure',es:'Ejercer presion'},
            {en:'Strike a balance',es:'Encontrar el equilibrio'},{en:'Bear the brunt',es:'Llevar la peor parte'},
            {en:'Shoulder the blame',es:'Cargar con la culpa'},{en:'Foster growth',es:'Fomentar el crecimiento'},
            {en:'Curb inflation',es:'Frenar la inflacion'},{en:'Bridge the gap',es:'Cerrar la brecha'},
            {en:'Voice concerns',es:'Expresar preocupaciones'},{en:'Uphold values',es:'Defender valores'},
            {en:'Grant permission',es:'Conceder permiso'},{en:'Incur costs',es:'Incurrir en costos'},
          ]},
        { id: 'phrasal_c1', titulo: 'Phrasal verbs formales', icono: '🔗',
          vocabulario: [
            {en:'Phase out',es:'Eliminar gradualmente'},{en:'Iron out',es:'Resolver (diferencias)'},
            {en:'Drum up',es:'Conseguir apoyo'},{en:'Single out',es:'Senalar / Destacar'},
            {en:'Factor in',es:'Tomar en cuenta'},{en:'Rule out',es:'Descartar'},
            {en:'Spell out',es:'Explicar en detalle'},{en:'Boil down to',es:'Reducirse a'},
            {en:'Account for',es:'Explicar / Representar'},{en:'Draw up',es:'Redactar (un documento)'},
            {en:'Set forth',es:'Exponer / Establecer'},{en:'Carry out',es:'Llevar a cabo'},
            {en:'Follow through',es:'Cumplir hasta el final'},{en:'Weigh up',es:'Sopesar'},
          ]},
        { id: 'environment_c1', titulo: 'Sostenibilidad y clima', icono: '♻️',
          vocabulario: [
            {en:'Mitigation',es:'Mitigacion'},{en:'Carbon neutrality',es:'Neutralidad de carbono'},
            {en:'Depletion',es:'Agotamiento (de recursos)'},{en:'Emission targets',es:'Metas de emisiones'},
            {en:'Renewable transition',es:'Transicion renovable'},{en:'Circular economy',es:'Economia circular'},
            {en:'Habitat loss',es:'Perdida de habitat'},{en:'Overfishing',es:'Sobrepesca'},
            {en:'Desertification',es:'Desertificacion'},{en:'Geoengineering',es:'Geoingenieria'},
            {en:'Environmental footprint',es:'Huella ambiental'},{en:'Greenwashing',es:'Ecoimpostura'},
            {en:'Resource scarcity',es:'Escasez de recursos'},{en:'Climate resilience',es:'Resiliencia climatica'},
          ]},
        { id: 'tech_ethics', titulo: 'Etica y tecnologia', icono: '🧬',
          vocabulario: [
            {en:'Bioethics',es:'Bioetica'},{en:'Gene editing',es:'Edicion genetica'},
            {en:'Surveillance',es:'Vigilancia'},{en:'Data privacy',es:'Privacidad de datos'},
            {en:'Algorithmic bias',es:'Sesgo algoritmico'},{en:'Accountability',es:'Rendicion de cuentas'},
            {en:'Informed consent',es:'Consentimiento informado'},{en:'Automation ethics',es:'Etica de la automatizacion'},
            {en:'Digital divide',es:'Brecha digital'},{en:'Misinformation',es:'Informacion erronea'},
            {en:'Intellectual property',es:'Propiedad intelectual'},{en:'Human oversight',es:'Supervision humana'},
            {en:'Dual-use technology',es:'Tecnologia de doble uso'},{en:'Precautionary principle',es:'Principio de precaucion'},
          ]},
        { id: 'nuanced_emotions', titulo: 'Emociones sutiles', icono: '🎭',
          vocabulario: [
            {en:'Apprehensive',es:'Aprensivo / Inquieto'},{en:'Despondent',es:'Desalentado'},
            {en:'Elated',es:'Eufórico'},{en:'Indifferent',es:'Indiferente'},
            {en:'Resentful',es:'Resentido'},{en:'Complacent',es:'Autocomplaciente'},
            {en:'Nostalgic',es:'Nostalgico'},{en:'Ambivalent',es:'Ambivalente'},
            {en:'Exasperated',es:'Exasperado'},{en:'Melancholic',es:'Melancolico'},
            {en:'Bewildered',es:'Desconcertado'},{en:'Serene',es:'Sereno'},
            {en:'Wistful',es:'Anhelante / Melancolico'},{en:'Disgruntled',es:'Descontento'},
          ]},
        { id: 'colloquial_english', titulo: 'Ingles coloquial y registro', icono: '😎',
          vocabulario: [
            {en:'Gonna / Wanna',es:'Voy a / Quiero (informal)'},{en:'Mate',es:'Amigo (britanico)'},
            {en:'No worries',es:'No hay problema'},{en:'Fancy doing something?',es:'¿Te apetece hacer algo?'},
            {en:'Gutted',es:'Devastado (informal)'},{en:'Chuffed',es:'Encantado (britanico)'},
            {en:'Knackered',es:'Agotado (britanico)'},{en:'Hang out',es:'Pasar el rato'},
            {en:'Chill out',es:'Relajarse'},{en:'What’s up?',es:'¿Que tal? / ¿Que pasa?'},
            {en:'My bad',es:'Culpa mia (informal)'},{en:'For real',es:'En serio'},
            {en:'It’s a no-brainer',es:'Es obvio / Sin pensarlo'},{en:'Long story short',es:'Resumiendo'},
          ]},
        { id: 'formal_correspondence', titulo: 'Correspondencia formal', icono: '✉️',
          vocabulario: [
            {en:'I am writing to enquire about',es:'Escribo para consultar sobre'},
            {en:'Please find attached',es:'Adjunto encontrara'},
            {en:'I look forward to hearing from you',es:'Quedo a la espera de su respuesta'},
            {en:'Yours faithfully',es:'Atentamente (destinatario desconocido)'},
            {en:'Yours sincerely',es:'Atentamente (destinatario conocido)'},
            {en:'To whom it may concern',es:'A quien corresponda'},
            {en:'I would be grateful if',es:'Le agradeceria si'},
            {en:'With reference to',es:'En referencia a'},
            {en:'I regret to inform you',es:'Lamento informarle'},
            {en:'I am pleased to confirm',es:'Me complace confirmar'},
            {en:'Should you require further information',es:'Si necesita mas informacion'},
            {en:'On behalf of',es:'En nombre de'},
          ]},
        { id: 'advanced_connectors', titulo: 'Conectores avanzados', icono: '🧵',
          vocabulario: [
            {en:'Albeit',es:'Aunque / Si bien'},{en:'Insofar as',es:'En la medida en que'},
            {en:'Thereby',es:'De ese modo'},{en:'Hence',es:'De ahi que / Por eso'},
            {en:'Conversely',es:'Por el contrario'},{en:'Likewise',es:'Del mismo modo'},
            {en:'Hitherto',es:'Hasta ahora'},{en:'Thus far',es:'Hasta el momento'},
            {en:'In lieu of',es:'En lugar de'},{en:'By virtue of',es:'En virtud de'},
            {en:'Granted that',es:'Concedido que / Si bien'},{en:'Be that as it may',es:'Sea como sea'},
            {en:'To that end',es:'Con ese fin'},{en:'In hindsight',es:'En retrospectiva'},
          ]},
        { id: 'euphemisms', titulo: 'Eufemismos y diplomacia', icono: '🤫',
          vocabulario: [
            {en:'To pass away',es:'Fallecer (eufemismo de morir)'},
            {en:'To let someone go',es:'Despedir a alguien (suave)'},
            {en:'Between jobs',es:'Desempleado (suave)'},
            {en:'Senior citizen',es:'Adulto mayor'},
            {en:'Economically disadvantaged',es:'De bajos recursos'},
            {en:'Correct me if I am wrong',es:'Corrigeme si me equivoco'},
            {en:'With all due respect',es:'Con todo respeto'},
            {en:'I see your point, but',es:'Entiendo tu punto, pero'},
            {en:'That is one way to look at it',es:'Esa es una forma de verlo'},
            {en:'It leaves room for improvement',es:'Deja margen de mejora'},
            {en:'Not my cup of tea',es:'No es lo mio (cortes)'},
            {en:'I beg to differ',es:'Me permito discrepar'},
          ]},
      ]
    });
    console.log('✅ Seed C1 completo — 21 temas');
    mongoose.disconnect();
  }).catch(e => { console.error(e.message); process.exit(1); });