const mongoose = require('mongoose');
require('dotenv').config();

mongoose.connect(process.env.MONGODB_URI)
  .then(() => { console.log('✅ MongoDB conectado'); seed(); })
  .catch(err => { console.error('❌', err.message); process.exit(1); });

const cursoSchema = new mongoose.Schema({ nivel: String, temas: Array }, { collection: 'cursos' });
const Curso = mongoose.model('Curso', cursoSchema);

async function seed() {
  await Curso.deleteOne({ nivel: 'A2' });

  await Curso.create({
    nivel: 'A2',
    temas: [
      {
        id: 'daily_routine',
        titulo: 'Rutina diaria',
        icono: '🌅',
        vocabulario: [
          { en: 'Wake up',      es: 'Despertar' },
          { en: 'Get up',       es: 'Levantarse' },
          { en: 'Brush teeth',  es: 'Cepillarse los dientes' },
          { en: 'Take a shower',es: 'Ducharse' },
          { en: 'Get dressed',  es: 'Vestirse' },
          { en: 'Have breakfast',es:'Desayunar' },
          { en: 'Go to work',   es: 'Ir al trabajo' },
          { en: 'Have lunch',   es: 'Almorzar' },
          { en: 'Come back home',es:'Regresar a casa' },
          { en: 'Have dinner',  es: 'Cenar' },
          { en: 'Go to bed',    es: 'Irse a dormir' },
          { en: 'Watch TV',     es: 'Ver televisión' },
          { en: 'Do homework',  es: 'Hacer tareas' },
          { en: 'Take a nap',   es: 'Tomar una siesta' },
          { en: 'Exercise',     es: 'Hacer ejercicio' },
        ]
      },
      {
        id: 'weather',
        titulo: 'El clima',
        icono: '☀️',
        vocabulario: [
          { en: 'Sunny',        es: 'Soleado' },
          { en: 'Cloudy',       es: 'Nublado' },
          { en: 'Rainy',        es: 'Lluvioso' },
          { en: 'Windy',        es: 'Ventoso' },
          { en: 'Stormy',       es: 'Tormentoso' },
          { en: 'Foggy',        es: 'Neblinoso' },
          { en: 'Snowy',        es: 'Nevado' },
          { en: 'Hot',          es: 'Caluroso' },
          { en: 'Cold',         es: 'Frío' },
          { en: 'Warm',         es: 'Cálido / Tibio' },
          { en: 'Humid',        es: 'Húmedo' },
          { en: 'Temperature',  es: 'Temperatura' },
          { en: 'Forecast',     es: 'Pronóstico' },
          { en: 'Rainbow',      es: 'Arcoíris' },
          { en: 'Thunder',      es: 'Trueno' },
          { en: 'Lightning',    es: 'Relámpago' },
        ]
      },
      {
        id: 'shopping',
        titulo: 'De compras',
        icono: '🛒',
        vocabulario: [
          { en: 'How much is it?',   es: '¿Cuánto cuesta?' },
          { en: 'Can I help you?',   es: '¿Puedo ayudarte?' },
          { en: 'I would like...',   es: 'Quisiera...' },
          { en: 'Do you have...?',   es: '¿Tienen...?' },
          { en: 'Receipt',           es: 'Recibo / Factura' },
          { en: 'Discount',          es: 'Descuento' },
          { en: 'On sale',           es: 'En oferta' },
          { en: 'Cash',              es: 'Efectivo' },
          { en: 'Credit card',       es: 'Tarjeta de crédito' },
          { en: 'Change',            es: 'Cambio / Vuelto' },
          { en: 'Size',              es: 'Talla / Tamaño' },
          { en: 'Fitting room',      es: 'Probador' },
          { en: 'Supermarket',       es: 'Supermercado' },
          { en: 'Aisle',             es: 'Pasillo' },
          { en: 'Checkout',          es: 'Caja registradora' },
          { en: 'Shopping cart',     es: 'Carrito de compras' },
        ]
      },
      {
        id: 'transport',
        titulo: 'Transporte y direcciones',
        icono: '🚌',
        vocabulario: [
          { en: 'Turn left',         es: 'Girar a la izquierda' },
          { en: 'Turn right',        es: 'Girar a la derecha' },
          { en: 'Go straight',       es: 'Seguir derecho' },
          { en: 'Bus stop',          es: 'Paradero de bus' },
          { en: 'Train station',     es: 'Estación de tren' },
          { en: 'Airport',           es: 'Aeropuerto' },
          { en: 'Taxi',              es: 'Taxi' },
          { en: 'Subway / Metro',    es: 'Metro' },
          { en: 'Ticket',            es: 'Tiquete / Boleto' },
          { en: 'Platform',          es: 'Andén / Plataforma' },
          { en: 'Departure',         es: 'Salida' },
          { en: 'Arrival',           es: 'Llegada' },
          { en: 'Delay',             es: 'Retraso' },
          { en: 'Corner',            es: 'Esquina' },
          { en: 'Block',             es: 'Cuadra' },
          { en: 'Crosswalk',         es: 'Paso peatonal' },
        ]
      },
      {
        id: 'health',
        titulo: 'Salud y síntomas',
        icono: '🏥',
        vocabulario: [
          { en: 'I have a headache',  es: 'Tengo dolor de cabeza' },
          { en: 'I have a fever',     es: 'Tengo fiebre' },
          { en: 'I feel sick',        es: 'Me siento mal' },
          { en: 'Stomachache',        es: 'Dolor de estómago' },
          { en: 'Sore throat',        es: 'Dolor de garganta' },
          { en: 'Cough',              es: 'Tos' },
          { en: 'Sneeze',             es: 'Estornudar' },
          { en: 'Prescription',       es: 'Receta médica' },
          { en: 'Medicine / Pill',    es: 'Medicina / Pastilla' },
          { en: 'Appointment',        es: 'Cita médica' },
          { en: 'Doctor',             es: 'Médico' },
          { en: 'Nurse',              es: 'Enfermero/a' },
          { en: 'Hospital',           es: 'Hospital' },
          { en: 'Allergy',            es: 'Alergia' },
          { en: 'Blood pressure',     es: 'Presión arterial' },
          { en: 'Injured',            es: 'Lesionado' },
        ]
      },
      {
        id: 'work',
        titulo: 'Trabajo y profesiones',
        icono: '💼',
        vocabulario: [
          { en: 'Teacher',        es: 'Profesor/a' },
          { en: 'Engineer',       es: 'Ingeniero/a' },
          { en: 'Doctor',         es: 'Médico/a' },
          { en: 'Lawyer',         es: 'Abogado/a' },
          { en: 'Chef',           es: 'Chef / Cocinero' },
          { en: 'Driver',         es: 'Conductor' },
          { en: 'Programmer',     es: 'Programador/a' },
          { en: 'Manager',        es: 'Gerente' },
          { en: 'Secretary',      es: 'Secretario/a' },
          { en: 'Accountant',     es: 'Contador/a' },
          { en: 'Salary',         es: 'Salario' },
          { en: 'Interview',      es: 'Entrevista' },
          { en: 'Resume / CV',    es: 'Hoja de vida' },
          { en: 'Meeting',        es: 'Reunión' },
          { en: 'Deadline',       es: 'Fecha límite' },
          { en: 'Promotion',      es: 'Ascenso' },
          { en: 'Colleague',      es: 'Compañero de trabajo' },
        ]
      },
      {
        id: 'hobbies',
        titulo: 'Hobbies y tiempo libre',
        icono: '🎨',
        vocabulario: [
          { en: 'Reading',        es: 'Leer' },
          { en: 'Cooking',        es: 'Cocinar' },
          { en: 'Painting',       es: 'Pintar' },
          { en: 'Dancing',        es: 'Bailar' },
          { en: 'Singing',        es: 'Cantar' },
          { en: 'Hiking',         es: 'Senderismo' },
          { en: 'Swimming',       es: 'Nadar' },
          { en: 'Cycling',        es: 'Ciclismo' },
          { en: 'Photography',    es: 'Fotografía' },
          { en: 'Gaming',         es: 'Videojuegos' },
          { en: 'Traveling',      es: 'Viajar' },
          { en: 'Gardening',      es: 'Jardinería' },
          { en: 'Knitting',       es: 'Tejer' },
          { en: 'Fishing',        es: 'Pescar' },
          { en: 'Yoga',           es: 'Yoga' },
        ]
      },
      {
        id: 'food_restaurant',
        titulo: 'Restaurante y comida',
        icono: '🍽️',
        vocabulario: [
          { en: 'Menu',              es: 'Menú / Carta' },
          { en: 'Waiter / Waitress', es: 'Mesero / Mesera' },
          { en: 'Order',             es: 'Pedir / Orden' },
          { en: 'Starter',           es: 'Entrada' },
          { en: 'Main course',       es: 'Plato principal' },
          { en: 'Dessert',           es: 'Postre' },
          { en: 'Bill / Check',      es: 'La cuenta' },
          { en: 'Tip',               es: 'Propina' },
          { en: 'Reservation',       es: 'Reservación' },
          { en: 'Spicy',             es: 'Picante' },
          { en: 'Grilled',           es: 'A la parrilla' },
          { en: 'Fried',             es: 'Frito' },
          { en: 'Boiled',            es: 'Hervido' },
          { en: 'Raw',               es: 'Crudo' },
          { en: 'Vegetarian',        es: 'Vegetariano' },
          { en: 'Gluten-free',       es: 'Sin gluten' },
        ]
      },
      {
        id: 'housing',
        titulo: 'Hogar y vivienda',
        icono: '🏠',
        vocabulario: [
          { en: 'Living room',    es: 'Sala' },
          { en: 'Bedroom',        es: 'Habitación' },
          { en: 'Bathroom',       es: 'Baño' },
          { en: 'Kitchen',        es: 'Cocina' },
          { en: 'Balcony',        es: 'Balcón' },
          { en: 'Garage',         es: 'Garaje' },
          { en: 'Garden',         es: 'Jardín' },
          { en: 'Rent',           es: 'Alquilar / Arriendo' },
          { en: 'Landlord',       es: 'Arrendador' },
          { en: 'Neighbor',       es: 'Vecino/a' },
          { en: 'Furniture',      es: 'Muebles' },
          { en: 'Sofa / Couch',   es: 'Sofá' },
          { en: 'Microwave',      es: 'Microondas' },
          { en: 'Washing machine',es: 'Lavadora' },
          { en: 'Air conditioner',es: 'Aire acondicionado' },
          { en: 'Heater',         es: 'Calentador' },
        ]
      },
      {
        id: 'past_tense',
        titulo: 'Pasado simple (verbos)',
        icono: '⏪',
        vocabulario: [
          { en: 'I went',         es: 'Fui / Fui (ir)' },
          { en: 'I ate',          es: 'Comí' },
          { en: 'I saw',          es: 'Vi' },
          { en: 'I had',          es: 'Tuve / Tenía' },
          { en: 'I said',         es: 'Dije' },
          { en: 'I came',         es: 'Vine' },
          { en: 'I took',         es: 'Tomé / Llevé' },
          { en: 'I made',         es: 'Hice' },
          { en: 'I gave',         es: 'Di' },
          { en: 'I knew',         es: 'Supe / Sabía' },
          { en: 'I thought',      es: 'Pensé / Creí' },
          { en: 'I bought',       es: 'Compré' },
          { en: 'I slept',        es: 'Dormí' },
          { en: 'I spoke',        es: 'Hablé' },
          { en: 'I wrote',        es: 'Escribí' },
          { en: 'I left',         es: 'Me fui / Salí' },
          { en: 'I found',        es: 'Encontré' },
          { en: 'I told',         es: 'Conté / Dije' },
        ]
      },
      {
        id: 'descriptions',
        titulo: 'Describir personas y lugares',
        icono: '👁️',
        vocabulario: [
          { en: 'Tall',           es: 'Alto/a' },
          { en: 'Short',          es: 'Bajo/a' },
          { en: 'Thin',           es: 'Delgado/a' },
          { en: 'Overweight',     es: 'Con sobrepeso' },
          { en: 'Curly hair',     es: 'Cabello rizado' },
          { en: 'Straight hair',  es: 'Cabello lacio' },
          { en: 'Bald',           es: 'Calvo' },
          { en: 'Beard',          es: 'Barba' },
          { en: 'Glasses',        es: 'Gafas' },
          { en: 'Beautiful',      es: 'Hermoso/a' },
          { en: 'Ugly',           es: 'Feo/a' },
          { en: 'Crowded',        es: 'Concurrido / Lleno' },
          { en: 'Quiet',          es: 'Tranquilo' },
          { en: 'Noisy',          es: 'Ruidoso' },
          { en: 'Modern',         es: 'Moderno' },
          { en: 'Ancient',        es: 'Antiguo' },
        ]
      },
      {
        id: 'grammar_a2',
        titulo: 'Gramática A2 esencial',
        icono: '📖',
        vocabulario: [
          { en: 'I was / I were',     es: 'Yo estaba / éramos (pasado to be)' },
          { en: 'I have been',        es: 'He estado (presente perfecto)' },
          { en: 'I am going to...',   es: 'Voy a... (futuro próximo)' },
          { en: 'I will...',          es: 'Voy a / Haré... (futuro simple)' },
          { en: 'Can you...?',        es: '¿Puedes...? (petición)' },
          { en: 'Could you...?',      es: '¿Podrías...? (petición formal)' },
          { en: 'Should I...?',       es: '¿Debería...?' },
          { en: 'There is / There are',es:'Hay (singular / plural)' },
          { en: 'How long does it take?',es:'¿Cuánto tiempo tarda?' },
          { en: 'What time does it open?',es:'¿A qué hora abre?' },
          { en: 'I prefer... to...',  es: 'Prefiero... a...' },
          { en: 'Would you like...?', es: '¿Le gustaría...?' },
          { en: 'Let me know',        es: 'Hazme saber / Avísame' },
          { en: 'As soon as possible',es: 'Lo antes posible' },
          { en: 'In my opinion',      es: 'En mi opinión' },
        ]
      },
      {
        id: 'feelings',
        titulo: 'Emociones y sentimientos',
        icono: '😊',
        vocabulario: [
          { en: 'Excited',        es: 'Emocionado/a' },
          { en: 'Worried',        es: 'Preocupado/a' },
          { en: 'Nervous',        es: 'Nervioso/a' },
          { en: 'Proud',          es: 'Orgulloso/a' },
          { en: 'Bored',          es: 'Aburrido/a' },
          { en: 'Surprised',      es: 'Sorprendido/a' },
          { en: 'Scared',         es: 'Asustado/a' },
          { en: 'Angry',          es: 'Enojado/a' },
          { en: 'Tired',          es: 'Cansado/a' },
          { en: 'Embarrassed',    es: 'Avergonzado/a' },
          { en: 'Jealous',        es: 'Celoso/a' },
          { en: 'Grateful',       es: 'Agradecido/a' },
          { en: 'Disappointed',   es: 'Decepcionado/a' },
          { en: 'Confident',      es: 'Seguro de sí mismo' },
        ]
      },
      {
        id: 'travel',
        titulo: 'Viajes y vacaciones',
        icono: '✈️',
        vocabulario: [
          { en: 'Luggage',        es: 'Equipaje' },
          { en: 'Passport',       es: 'Pasaporte' },
          { en: 'Suitcase',       es: 'Maleta' },
          { en: 'Backpack',       es: 'Mochila' },
          { en: 'Hotel',          es: 'Hotel' },
          { en: 'Booking',        es: 'Reserva' },
          { en: 'Check-in',       es: 'Registro de entrada' },
          { en: 'Check-out',      es: 'Salida del hotel' },
          { en: 'Tourist',        es: 'Turista' },
          { en: 'Sightseeing',    es: 'Turismo / Pasear' },
          { en: 'Map',            es: 'Mapa' },
          { en: 'Beach',          es: 'Playa' },
          { en: 'Trip',           es: 'Viaje' },
          { en: 'Abroad',         es: 'En el extranjero' },
          { en: 'Souvenir',       es: 'Recuerdo' },
        ]
      },
      {
        id: 'technology',
        titulo: 'Tecnología e internet',
        icono: '💻',
        vocabulario: [
          { en: 'Computer',       es: 'Computador' },
          { en: 'Laptop',         es: 'Portátil' },
          { en: 'Screen',         es: 'Pantalla' },
          { en: 'Keyboard',       es: 'Teclado' },
          { en: 'Mouse',          es: 'Ratón / Mouse' },
          { en: 'Password',       es: 'Contraseña' },
          { en: 'Download',       es: 'Descargar' },
          { en: 'Upload',         es: 'Subir / Cargar' },
          { en: 'Charger',        es: 'Cargador' },
          { en: 'Headphones',     es: 'Audífonos' },
          { en: 'Wireless',       es: 'Inalámbrico' },
          { en: 'Email',          es: 'Correo electrónico' },
          { en: 'Website',        es: 'Sitio web' },
          { en: 'File',           es: 'Archivo' },
          { en: 'Settings',       es: 'Configuración' },
        ]
      },
      {
        id: 'school',
        titulo: 'Escuela y estudios',
        icono: '🎓',
        vocabulario: [
          { en: 'Subject',        es: 'Materia / Asignatura' },
          { en: 'Grade',          es: 'Nota / Calificación' },
          { en: 'Exam',           es: 'Examen' },
          { en: 'Homework',       es: 'Tarea' },
          { en: 'Notebook',       es: 'Cuaderno' },
          { en: 'Classmate',      es: 'Compañero de clase' },
          { en: 'Schedule',       es: 'Horario' },
          { en: 'Break',          es: 'Descanso / Recreo' },
          { en: 'Library',        es: 'Biblioteca' },
          { en: 'To learn',       es: 'Aprender' },
          { en: 'To teach',       es: 'Enseñar' },
          { en: 'To study',       es: 'Estudiar' },
          { en: 'To pass',        es: 'Aprobar' },
          { en: 'To fail',        es: 'Reprobar' },
        ]
      },
      {
        id: 'nature',
        titulo: 'Naturaleza y animales',
        icono: '🌳',
        vocabulario: [
          { en: 'Mountain',       es: 'Montaña' },
          { en: 'River',          es: 'Río' },
          { en: 'Forest',         es: 'Bosque' },
          { en: 'Lake',           es: 'Lago' },
          { en: 'Island',         es: 'Isla' },
          { en: 'Desert',         es: 'Desierto' },
          { en: 'Waterfall',      es: 'Cascada' },
          { en: 'Horse',          es: 'Caballo' },
          { en: 'Cow',            es: 'Vaca' },
          { en: 'Monkey',         es: 'Mono' },
          { en: 'Lion',           es: 'León' },
          { en: 'Snake',          es: 'Serpiente' },
          { en: 'Butterfly',      es: 'Mariposa' },
          { en: 'Turtle',         es: 'Tortuga' },
          { en: 'Whale',          es: 'Ballena' },
        ]
      },
      {
        id: 'city',
        titulo: 'Lugares de la ciudad',
        icono: '🏙️',
        vocabulario: [
          { en: 'Bank',           es: 'Banco' },
          { en: 'Post office',    es: 'Oficina de correos' },
          { en: 'Museum',         es: 'Museo' },
          { en: 'Park',           es: 'Parque' },
          { en: 'Bridge',         es: 'Puente' },
          { en: 'Church',         es: 'Iglesia' },
          { en: 'Town hall',      es: 'Alcaldía' },
          { en: 'Police station', es: 'Estación de policía' },
          { en: 'Fire station',   es: 'Estación de bomberos' },
          { en: 'Sidewalk',       es: 'Acera / Andén' },
          { en: 'Traffic light',  es: 'Semáforo' },
          { en: 'Square',         es: 'Plaza' },
          { en: 'Building',       es: 'Edificio' },
          { en: 'Downtown',       es: 'Centro de la ciudad' },
        ]
      },
      {
        id: 'comparatives',
        titulo: 'Comparativos y superlativos',
        icono: '⚖️',
        vocabulario: [
          { en: 'Bigger than',      es: 'Más grande que' },
          { en: 'Smaller than',     es: 'Más pequeño que' },
          { en: 'Better than',      es: 'Mejor que' },
          { en: 'Worse than',       es: 'Peor que' },
          { en: 'Faster than',      es: 'Más rápido que' },
          { en: 'More expensive',   es: 'Más caro' },
          { en: 'Cheaper than',     es: 'Más barato que' },
          { en: 'The best',         es: 'El mejor' },
          { en: 'The worst',        es: 'El peor' },
          { en: 'The biggest',      es: 'El más grande' },
          { en: 'The most beautiful',es:'El más hermoso' },
          { en: 'As big as',        es: 'Tan grande como' },
          { en: 'Older than',       es: 'Mayor que / Más viejo que' },
          { en: 'Younger than',     es: 'Menor que / Más joven que' },
        ]
      },
      {
        id: 'present_continuous',
        titulo: 'Presente continuo',
        icono: '▶️',
        vocabulario: [
          { en: 'I am working',     es: 'Estoy trabajando' },
          { en: 'I am eating',      es: 'Estoy comiendo' },
          { en: 'I am studying',    es: 'Estoy estudiando' },
          { en: 'She is reading',   es: 'Ella está leyendo' },
          { en: 'He is sleeping',   es: 'Él está durmiendo' },
          { en: 'We are playing',   es: 'Estamos jugando' },
          { en: 'They are talking', es: 'Ellos están hablando' },
          { en: 'It is raining',    es: 'Está lloviendo' },
          { en: 'I am listening',   es: 'Estoy escuchando' },
          { en: 'She is cooking',   es: 'Ella está cocinando' },
          { en: 'We are learning',  es: 'Estamos aprendiendo' },
          { en: 'He is driving',    es: 'Él está conduciendo' },
          { en: 'I am waiting',     es: 'Estoy esperando' },
          { en: 'They are running', es: 'Ellos están corriendo' },
        ]
      },
      {
        id: 'phrasal_verbs',
        titulo: 'Phrasal verbs básicos',
        icono: '🔗',
        vocabulario: [
          { en: 'Turn on',        es: 'Encender' },
          { en: 'Turn off',       es: 'Apagar' },
          { en: 'Put on',         es: 'Ponerse (ropa)' },
          { en: 'Take off',       es: 'Quitarse (ropa)' },
          { en: 'Look for',       es: 'Buscar' },
          { en: 'Find out',       es: 'Descubrir / Averiguar' },
          { en: 'Give up',        es: 'Rendirse' },
          { en: 'Pick up',        es: 'Recoger' },
          { en: 'Come in',        es: 'Entrar' },
          { en: 'Go out',         es: 'Salir' },
          { en: 'Sit down',       es: 'Sentarse' },
          { en: 'Stand up',       es: 'Ponerse de pie' },
          { en: 'Hurry up',       es: 'Apurarse' },
          { en: 'Slow down',      es: 'Bajar la velocidad' },
        ]
      },
    ]
  });

  console.log('✅ Seed A2 completado — 21 temas insertados en MongoDB');
  mongoose.disconnect();
}