const mongoose = require('mongoose');
require('dotenv').config();
mongoose.connect(process.env.MONGODB_URI)
  .then(async () => {
    const db = mongoose.connection.db;
    await db.collection('cursos').deleteOne({ nivel: 'B2' });
    await db.collection('cursos').insertOne({
      nivel: 'B2',
      temas: [
        { id: 'economics', titulo: 'Economia y finanzas', icono: '💹',
          vocabulario: [
            {en:'Inflation',es:'Inflacion'},{en:'Recession',es:'Recesion'},{en:'GDP',es:'PIB'},
            {en:'Investment',es:'Inversion'},{en:'Stock market',es:'Bolsa de valores'},{en:'Interest rate',es:'Tasa de interes'},
            {en:'Budget',es:'Presupuesto'},{en:'Deficit',es:'Deficit'},{en:'Surplus',es:'Superavit'},
            {en:'Entrepreneur',es:'Empresario'},{en:'Venture capital',es:'Capital de riesgo'},{en:'Merger',es:'Fusion empresarial'},
          ]},
        { id: 'law_politics', titulo: 'Derecho y politica', icono: '⚖️',
          vocabulario: [
            {en:'Legislation',es:'Legislacion'},{en:'Constitution',es:'Constitucion'},{en:'Jurisdiction',es:'Jurisdiccion'},
            {en:'Democracy',es:'Democracia'},{en:'Corruption',es:'Corrupcion'},{en:'Sovereignty',es:'Soberania'},
            {en:'Treaty',es:'Tratado'},{en:'Referendum',es:'Referendum'},{en:'Amendment',es:'Enmienda'},
            {en:'Sanctions',es:'Sanciones'},{en:'Diplomacy',es:'Diplomacia'},{en:'Lobbying',es:'Cabildeo'},
          ]},
        { id: 'science', titulo: 'Ciencia e investigacion', icono: '🔬',
          vocabulario: [
            {en:'Hypothesis',es:'Hipotesis'},{en:'Methodology',es:'Metodologia'},{en:'Experiment',es:'Experimento'},
            {en:'Evidence',es:'Evidencia'},{en:'Phenomenon',es:'Fenomeno'},{en:'Analysis',es:'Analisis'},
            {en:'Conclusion',es:'Conclusion'},{en:'Peer review',es:'Revision por pares'},{en:'Breakthrough',es:'Avance cientifico'},
            {en:'Genome',es:'Genoma'},{en:'Quantum',es:'Cuantico'},{en:'Nanotechnology',es:'Nanotecnologia'},
          ]},
        { id: 'psychology', titulo: 'Psicologia y comportamiento', icono: '🧠',
          vocabulario: [
            {en:'Cognitive',es:'Cognitivo'},{en:'Behavior',es:'Comportamiento'},{en:'Motivation',es:'Motivacion'},
            {en:'Perception',es:'Percepcion'},{en:'Subconscious',es:'Subconsciente'},{en:'Empathy',es:'Empatia'},
            {en:'Resilience',es:'Resiliencia'},{en:'Trauma',es:'Trauma'},{en:'Anxiety',es:'Ansiedad'},
            {en:'Self-esteem',es:'Autoestima'},{en:'Bias',es:'Sesgo'},{en:'Stereotype',es:'Estereotipo'},
          ]},
        { id: 'arts_literature', titulo: 'Arte y literatura', icono: '🎨',
          vocabulario: [
            {en:'Masterpiece',es:'Obra maestra'},{en:'Aesthetic',es:'Estetica'},{en:'Metaphor',es:'Metafora'},
            {en:'Narrative',es:'Narrativa'},{en:'Genre',es:'Genero literario'},{en:'Symbolism',es:'Simbolismo'},
            {en:'Protagonist',es:'Protagonista'},{en:'Plot',es:'Trama'},{en:'Irony',es:'Ironia'},
            {en:'Satire',es:'Satira'},{en:'Abstract',es:'Abstracto'},{en:'Contemporary',es:'Contemporaneo'},
          ]},
        { id: 'globalization', titulo: 'Globalizacion', icono: '🌐',
          vocabulario: [
            {en:'Multinational',es:'Multinacional'},{en:'Trade agreement',es:'Tratado comercial'},{en:'Outsourcing',es:'Subcontratacion'},
            {en:'Migration',es:'Migracion'},{en:'Cultural exchange',es:'Intercambio cultural'},{en:'Inequality',es:'Desigualdad'},
            {en:'Poverty',es:'Pobreza'},{en:'Human rights',es:'Derechos humanos'},{en:'Refugee',es:'Refugiado'},
            {en:'Integration',es:'Integracion'},{en:'Protectionism',es:'Proteccionismo'},{en:'Tariff',es:'Arancel'},
          ]},
        { id: 'idioms', titulo: 'Modismos avanzados', icono: '🗣️',
          vocabulario: [
            {en:'Break a leg',es:'Buena suerte'},{en:'Hit the nail on the head',es:'Dar en el clavo'},
            {en:'Under the weather',es:'Sentirse mal'},{en:'Bite the bullet',es:'Aguantar el dolor'},
            {en:'Burn bridges',es:'Quemar las naves'},{en:'Cut to the chase',es:'Ir al grano'},
            {en:'On the fence',es:'Indeciso'},{en:'Miss the boat',es:'Perder la oportunidad'},
            {en:'Pull strings',es:'Mover influencias'},{en:'Read between the lines',es:'Leer entre lineas'},
            {en:'Spill the beans',es:'Revelar el secreto'},{en:'Take with a grain of salt',es:'Tomar con cautela'},
          ]},
        { id: 'formal_writing', titulo: 'Escritura formal', icono: '✍️',
          vocabulario: [
            {en:'Furthermore',es:'Ademas'},{en:'Nevertheless',es:'Sin embargo'},{en:'Subsequently',es:'Posteriormente'},
            {en:'Aforementioned',es:'Anteriormente mencionado'},{en:'Notwithstanding',es:'No obstante'},
            {en:'Herein',es:'Aqui dentro'},{en:'Pursuant to',es:'De conformidad con'},{en:'Whereby',es:'Por lo cual'},
            {en:'Henceforth',es:'De ahora en adelante'},{en:'Whereas',es:'Considerando que'},
            {en:'Thereof',es:'De ello'},{en:'Forthwith',es:'Inmediatamente'},
          ]},
        { id: 'debate', titulo: 'Debate y argumentacion', icono: '🎤',
          vocabulario: [
            {en:'Counterargument',es:'Contraargumento'},{en:'Evidence',es:'Evidencia'},{en:'Premise',es:'Premisa'},
            {en:'Inference',es:'Inferencia'},{en:'Fallacy',es:'Falacia'},{en:'Assertion',es:'Aseveracion'},
            {en:'Rebut',es:'Refutar'},{en:'Concede',es:'Conceder'},{en:'Elaborate',es:'Elaborar'},
            {en:'Substantiate',es:'Fundamentar'},{en:'Implication',es:'Implicacion'},{en:'Consensus',es:'Consenso'},
          ]},
        { id: 'business_english', titulo: 'Ingles de negocios', icono: '🤝',
          vocabulario: [
            {en:'Stakeholder',es:'Parte interesada'},{en:'ROI',es:'Retorno de inversion'},{en:'KPI',es:'Indicador clave'},
            {en:'Benchmark',es:'Referencia de rendimiento'},{en:'Scalable',es:'Escalable'},{en:'Revenue',es:'Ingresos'},
            {en:'Brand awareness',es:'Reconocimiento de marca'},{en:'Market share',es:'Cuota de mercado'},
            {en:'Pitch',es:'Presentacion de negocio'},{en:'Due diligence',es:'Debida diligencia'},
            {en:'Equity',es:'Capital propio'},{en:'Leverage',es:'Apalancamiento'},
          ]},
        { id: 'passive_voice', titulo: 'Voz pasiva avanzada', icono: '🔄',
          vocabulario: [
            {en:'It has been announced',es:'Ha sido anunciado'},{en:'The project was launched',es:'El proyecto fue lanzado'},
            {en:'They are being trained',es:'Estan siendo entrenados'},{en:'It will be completed',es:'Sera completado'},
            {en:'The law was amended',es:'La ley fue enmendada'},{en:'Results have been published',es:'Los resultados han sido publicados'},
            {en:'It is widely believed',es:'Se cree ampliamente'},{en:'The contract was terminated',es:'El contrato fue terminado'},
            {en:'Mistakes were made',es:'Se cometieron errores'},{en:'A solution has been found',es:'Se ha encontrado una solucion'},
            {en:'The meeting was postponed',es:'La reunion fue pospuesta'},{en:'It is expected that',es:'Se espera que'},
          ]},
        { id: 'grammar_b2', titulo: 'Gramatica B2', icono: '📚',
          vocabulario: [
            {en:'I should have known',es:'Deberia haber sabido'},{en:'Had I known',es:'Si hubiera sabido'},
            {en:'It would have been',es:'Habria sido'},{en:'She could have told me',es:'Ella podria haberme dicho'},
            {en:'They must have left',es:'Deben haber salido'},{en:'I ought to have called',es:'Deberia haber llamado'},
            {en:'He need not have worried',es:'El no necesitaba haberse preocupado'},
            {en:'If it were not for',es:'Si no fuera por'},{en:'I am supposed to',es:'Se supone que debo'},
            {en:'There is no point in',es:'No tiene sentido'},{en:'It goes without saying',es:'Huelga decir'},
            {en:'Not only did he',es:'No solo el'},
          ]},
        { id: 'health_medicine', titulo: 'Medicina y salud avanzada', icono: '🏥',
          vocabulario: [
            {en:'Diagnosis',es:'Diagnostico'},{en:'Treatment',es:'Tratamiento'},{en:'Surgery',es:'Cirugia'},
            {en:'Side effects',es:'Efectos secundarios'},{en:'Recovery',es:'Recuperacion'},{en:'Symptoms',es:'Sintomas'},
            {en:'Chronic',es:'Cronico'},{en:'Contagious',es:'Contagioso'},{en:'Immune system',es:'Sistema inmunologico'},
            {en:'Specialist',es:'Especialista'},{en:'Painkiller',es:'Analgesico'},{en:'Dosage',es:'Dosis'},
            {en:'Outbreak',es:'Brote epidemico'},{en:'To undergo surgery',es:'Someterse a cirugia'},
          ]},
        { id: 'advertising', titulo: 'Publicidad y consumo', icono: '📢',
          vocabulario: [
            {en:'Target audience',es:'Publico objetivo'},{en:'Slogan',es:'Eslogan'},{en:'Consumerism',es:'Consumismo'},
            {en:'Misleading',es:'Enganoso'},{en:'Brand loyalty',es:'Fidelidad a la marca'},{en:'Campaign',es:'Campana'},
            {en:'Endorsement',es:'Patrocinio / Respaldo'},{en:'Persuasive',es:'Persuasivo'},{en:'Billboard',es:'Valla publicitaria'},
            {en:'Word of mouth',es:'De boca en boca'},{en:'Impulse buying',es:'Compra impulsiva'},{en:'Sponsor',es:'Patrocinador'},
            {en:'Catchy',es:'Pegadizo'},{en:'To launch a product',es:'Lanzar un producto'},
          ]},
        { id: 'employment', titulo: 'Mundo laboral moderno', icono: '👔',
          vocabulario: [
            {en:'Recruitment',es:'Reclutamiento'},{en:'Layoff',es:'Despido masivo'},{en:'Freelance',es:'Trabajo independiente'},
            {en:'Work-life balance',es:'Equilibrio vida-trabajo'},{en:'Remote work',es:'Trabajo remoto'},{en:'Burnout',es:'Agotamiento laboral'},
            {en:'Internship',es:'Pasantia'},{en:'Retirement',es:'Jubilacion'},{en:'Overtime',es:'Horas extra'},
            {en:'Wage gap',es:'Brecha salarial'},{en:'Job security',es:'Estabilidad laboral'},{en:'Networking',es:'Hacer contactos'},
            {en:'To quit',es:'Renunciar'},{en:'To get hired',es:'Ser contratado'},
          ]},
        { id: 'society_urban', titulo: 'Sociedad y vida urbana', icono: '🏙️',
          vocabulario: [
            {en:'Infrastructure',es:'Infraestructura'},{en:'Commute',es:'Trayecto al trabajo'},{en:'Overcrowded',es:'Sobrepoblado'},
            {en:'Housing shortage',es:'Escasez de vivienda'},{en:'Urban sprawl',es:'Expansion urbana'},{en:'Public transport',es:'Transporte publico'},
            {en:'Traffic congestion',es:'Congestion vehicular'},{en:'Suburbs',es:'Suburbios / Afueras'},{en:'Slum',es:'Barrio marginal'},
            {en:'Cost of living',es:'Costo de vida'},{en:'Homelessness',es:'Indigencia'},{en:'Community',es:'Comunidad'},
            {en:'Neighborhood watch',es:'Vigilancia vecinal'},{en:'Quality of life',es:'Calidad de vida'},
          ]},
        { id: 'phrasal_b2', titulo: 'Phrasal verbs avanzados', icono: '🔗',
          vocabulario: [
            {en:'Come up with',es:'Idear / Proponer'},{en:'Put up with',es:'Tolerar / Aguantar'},
            {en:'Get away with',es:'Salirse con la suya'},{en:'Look down on',es:'Menospreciar'},
            {en:'Back down',es:'Echarse atras'},{en:'Call off',es:'Cancelar'},
            {en:'Turn out',es:'Resultar'},{en:'Bring up',es:'Mencionar / Criar'},
            {en:'Do without',es:'Prescindir de'},{en:'Fall through',es:'Fracasar (un plan)'},
            {en:'Live up to',es:'Estar a la altura de'},{en:'Run into',es:'Encontrarse con'},
            {en:'Sort out',es:'Resolver / Arreglar'},{en:'Take over',es:'Tomar el control'},
          ]},
        { id: 'collocations', titulo: 'Colocaciones comunes', icono: '🧩',
          vocabulario: [
            {en:'Make a decision',es:'Tomar una decision'},{en:'Do research',es:'Investigar'},
            {en:'Take responsibility',es:'Asumir responsabilidad'},{en:'Pay attention',es:'Prestar atencion'},
            {en:'Have an impact',es:'Tener un impacto'},{en:'Reach an agreement',es:'Llegar a un acuerdo'},
            {en:'Raise awareness',es:'Crear conciencia'},{en:'Meet a deadline',es:'Cumplir un plazo'},
            {en:'Keep in touch',es:'Mantenerse en contacto'},{en:'Break the news',es:'Dar la noticia'},
            {en:'Catch someone’s eye',es:'Llamar la atencion de alguien'},{en:'Draw a conclusion',es:'Sacar una conclusion'},
            {en:'Set an example',es:'Dar ejemplo'},{en:'Take advantage of',es:'Aprovechar'},
          ]},
        { id: 'reporting_verbs', titulo: 'Verbos de reporte', icono: '💬',
          vocabulario: [
            {en:'To claim',es:'Afirmar / Alegar'},{en:'To deny',es:'Negar'},{en:'To acknowledge',es:'Reconocer'},
            {en:'To insist',es:'Insistir'},{en:'To imply',es:'Insinuar / Dar a entender'},{en:'To assure',es:'Asegurar'},
            {en:'To confess',es:'Confesar'},{en:'To urge',es:'Instar / Exhortar'},{en:'To point out',es:'Senalar'},
            {en:'To blame',es:'Culpar'},{en:'To praise',es:'Elogiar'},{en:'To accuse',es:'Acusar'},
            {en:'To recommend',es:'Recomendar'},{en:'To announce',es:'Anunciar'},
          ]},
        { id: 'word_formation', titulo: 'Formacion de palabras', icono: '🔤',
          vocabulario: [
            {en:'Unbelievable',es:'Increible (un- + -able)'},{en:'Careless',es:'Descuidado (-less)'},
            {en:'Strengthen',es:'Fortalecer (-en)'},{en:'Misunderstand',es:'Malinterpretar (mis-)'},
            {en:'Overwork',es:'Trabajar en exceso (over-)'},{en:'Underestimate',es:'Subestimar (under-)'},
            {en:'Meaningful',es:'Significativo (-ful)'},{en:'Happiness',es:'Felicidad (-ness)'},
            {en:'Friendship',es:'Amistad (-ship)'},{en:'Development',es:'Desarrollo (-ment)'},
            {en:'Responsibility',es:'Responsabilidad (-ity)'},{en:'Rewrite',es:'Reescribir (re-)'},
            {en:'Disagreement',es:'Desacuerdo (dis-)'},{en:'Effectiveness',es:'Eficacia (-ness)'},
          ]},
        { id: 'advanced_structures', titulo: 'Estructuras avanzadas', icono: '🏗️',
          vocabulario: [
            {en:'Rarely have I seen',es:'Rara vez he visto (inversion)'},
            {en:'Never before had we',es:'Nunca antes habiamos (inversion)'},
            {en:'What I need is time',es:'Lo que necesito es tiempo (clausula hendida)'},
            {en:'It was John who called',es:'Fue John quien llamo (enfasis)'},
            {en:'Having finished the work',es:'Habiendo terminado el trabajo'},
            {en:'Being unable to attend',es:'Al no poder asistir'},
            {en:'No sooner had I arrived',es:'Apenas habia llegado'},
            {en:'Little did she know',es:'Poco sabia ella'},
            {en:'Under no circumstances',es:'Bajo ninguna circunstancia'},
            {en:'Only then did I realize',es:'Solo entonces me di cuenta'},
            {en:'Seldom do we consider',es:'Rara vez consideramos'},
            {en:'The sooner, the better',es:'Cuanto antes, mejor'},
          ]},
      ]
    });
    console.log('✅ Seed B2 completo — 21 temas');
    mongoose.disconnect();
  }).catch(e => { console.error(e.message); process.exit(1); });