const mongoose = require('mongoose');
require('dotenv').config();

mongoose.connect(process.env.MONGODB_URI)
  .then(() => { console.log('✅ MongoDB conectado'); seed(); })
  .catch(err => { console.error('❌', err.message); process.exit(1); });

const CityDistrict = require('../models/CityDistrict');
const CityMission  = require('../models/CityMission');

// ─── Distritos (desbloqueo POR EQUIPO, data-driven) ───
const DISTRITOS = [
  { id:'restaurant',   nombre:'Restaurant',   nombreEs:'Restaurante',  tema:'Ordering food',      temaEs:'Pedir comida',        icono:'🍽️', color:'#f59e0b', orden:1, requiereCompletados:0 },
  { id:'airport',      nombre:'Airport',      nombreEs:'Aeropuerto',   tema:'Travel',             temaEs:'Viajes',              icono:'✈️', color:'#06b6d4', orden:2, requiereCompletados:0 },
  { id:'mall',         nombre:'Mall',         nombreEs:'Centro comercial', tema:'Shopping & comparatives', temaEs:'Compras y comparativos', icono:'🛍️', color:'#8b5cf6', orden:3, requiereCompletados:0 },
  { id:'station',      nombre:'Station',      nombreEs:'Estación',     tema:'Directions',         temaEs:'Direcciones',         icono:'🚉', color:'#10b981', orden:4, requiereCompletados:3 },
  { id:'hospital',     nombre:'Hospital',     nombreEs:'Hospital',     tema:'Health',             temaEs:'Salud',               icono:'🏥', color:'#ef4444', orden:5, requiereCompletados:3 },
  { id:'neighborhood', nombre:'Neighborhood', nombreEs:'El barrio',    tema:'Past simple',        temaEs:'Pasado simple',       icono:'🏘️', color:'#ec4899', orden:6, requiereCompletados:3 },
];

// Paso "teach" genérico: {word} se reemplaza en vivo con una carta
// aportada por OTRO compañero (diccionario del equipo).
const TEACH = (ctx) => ({
  type:'teach',
  say:  `Teacher time! Teach "{word}" to your team. Which question helps them practice it?`,
  sayEs:`¡Hora de enseñar! Enseña "{word}" a tu equipo. ¿Qué pregunta les ayuda a practicarla?`,
  opts: [
    `Can you use "{word}" in a sentence about ${ctx}?`,
    `Do you know "{word}"? Yes or no?`,
    `"{word}" is easy, right?`,
  ],
  answer: 0,
  feedback: {
    en: 'A good teaching question makes your team USE the word, not just say yes or no.',
    es: 'Una buena pregunta hace que tu equipo USE la palabra, no que solo diga sí o no.',
  },
  card: { en:'', es:'' },
});

const MISIONES = [
  // ═══════════ RESTAURANT — Ordering food ═══════════
  { distrito:'restaurant', orden:1, titulo:'A table for two', tituloEs:'Una mesa para dos', npc:'Waiter Sam', npcIcon:'🧑‍🍳', pasos:[
    { type:'choice', say:'Good evening! How many people?', sayEs:'¡Buenas noches! ¿Cuántas personas?',
      opts:['A table for two, please.','I am two people.','Give me table.','Two table now.'], answer:0,
      feedback:{ en:'Use "A table for two, please" — polite requests end with "please".', es:'Usa "A table for two, please" — las peticiones educadas terminan con "please".' },
      card:{ en:'A table for two, please', es:'Una mesa para dos, por favor' } },
    { type:'build', say:'Order a drink.', sayEs:'Pide una bebida.',
      words:['like','I','a','would','lemonade'], answer:'I would like a lemonade',
      feedback:{ en:'"I would like..." is the polite way to order.', es:'"I would like..." es la forma educada de pedir.' },
      card:{ en:'I would like...', es:'Quisiera...' } },
    { type:'listen', say:'The soup of the day is tomato.', sayEs:'Escucha al mesero y elige lo que dijo.',
      opts:['The soup of the day is tomato.','The soup of the day is potato.','The salad of the day is tomato.'], answer:0,
      feedback:{ en:'"Soup of the day" is the special soup today.', es:'"Soup of the day" es la sopa especial de hoy.' },
      card:{ en:'Soup of the day', es:'Sopa del día' } },
    TEACH('food'),
  ]},
  { distrito:'restaurant', orden:2, titulo:'The bill, please', tituloEs:'La cuenta, por favor', npc:'Waiter Sam', npcIcon:'🧑‍🍳', pasos:[
    { type:'choice', say:'Did you enjoy your meal?', sayEs:'¿Disfrutó su comida?',
      opts:['Yes, it was delicious!','Yes, it is deliciouses.','Yes, he was delicious.','Yes, I delicious.'], answer:0,
      feedback:{ en:'"It was delicious" — use "was" for past, "it" for the meal.', es:'"It was delicious" — usa "was" para pasado, "it" para la comida.' },
      card:{ en:'It was delicious', es:'Estuvo delicioso' } },
    { type:'build', say:'Ask for the bill.', sayEs:'Pide la cuenta.',
      words:['the','please','bill,','Can','have','I'], answer:'Can I have the bill, please',
      feedback:{ en:'"Can I have..." is how you ask for something politely.', es:'"Can I have..." es como pides algo educadamente.' },
      card:{ en:'Can I have the bill, please?', es:'¿Me trae la cuenta, por favor?' } },
    { type:'listen', say:'Would you like anything else?', sayEs:'Escucha la pregunta del mesero.',
      opts:['Would you like anything else?','Would you like something here?','Do you like anything else?'], answer:0,
      feedback:{ en:'"Would you like...?" is a polite offer.', es:'"Would you like...?" es un ofrecimiento educado.' },
      card:{ en:'Anything else?', es:'¿Algo más?' } },
    TEACH('a restaurant'),
  ]},
  { distrito:'restaurant', orden:3, titulo:'Allergies & requests', tituloEs:'Alergias y peticiones', npc:'Chef Lu', npcIcon:'👩‍🍳', pasos:[
    { type:'choice', say:'Any allergies I should know about?', sayEs:'¿Alguna alergia que deba saber?',
      opts:['I am allergic to peanuts.','I am allergy peanuts.','Peanuts is allergic to me.','Me allergic peanuts.'], answer:0,
      feedback:{ en:'"I am allergic TO..." — always use "to" after allergic.', es:'"I am allergic TO..." — siempre va "to" después de allergic.' },
      card:{ en:'I am allergic to...', es:'Soy alérgico a...' } },
    { type:'build', say:'Ask for no onions.', sayEs:'Pide sin cebolla.',
      words:['it','onions,','Without','please'], answer:'Without onions, please',
      feedback:{ en:'"Without" means the food does NOT have that ingredient.', es:'"Without" significa que la comida NO lleva ese ingrediente.' },
      card:{ en:'Without onions, please', es:'Sin cebolla, por favor' } },
    { type:'listen', say:'The dessert comes with ice cream.', sayEs:'Escucha lo que dice la chef.',
      opts:['The dessert comes with ice cream.','The dessert comes with iced tea.','The desert is very hot.'], answer:0,
      feedback:{ en:'"Comes with" = it is included.', es:'"Comes with" = viene incluido.' },
      card:{ en:'It comes with...', es:'Viene con...' } },
  ]},

  // ═══════════ AIRPORT — Travel ═══════════
  { distrito:'airport', orden:1, titulo:'Check-in time', tituloEs:'Hora del check-in', npc:'Agent Maya', npcIcon:'👩‍✈️', pasos:[
    { type:'choice', say:'Good morning! May I see your passport?', sayEs:'¡Buenos días! ¿Me muestra su pasaporte?',
      opts:['Here you are.','Here I am.','This is me.','You see it.'], answer:0,
      feedback:{ en:'"Here you are" is what you say when you hand something to someone.', es:'"Here you are" se dice al entregar algo a alguien.' },
      card:{ en:'Here you are', es:'Aquí tiene' } },
    { type:'build', say:'Ask about your gate.', sayEs:'Pregunta por tu puerta de embarque.',
      words:['is','gate?','Where','my'], answer:'Where is my gate',
      feedback:{ en:'Questions with "where" ask about places: Where + is + thing.', es:'Las preguntas con "where" son de lugares: Where + is + cosa.' },
      card:{ en:'Where is my gate?', es:'¿Dónde está mi puerta?' } },
    { type:'listen', say:'Your flight boards at gate twelve.', sayEs:'Escucha a la agente.',
      opts:['Your flight boards at gate twelve.','Your flight boards at gate twenty.','Your flight lands at gate twelve.'], answer:0,
      feedback:{ en:'"Boards" = passengers enter the plane. Twelve = 12, twenty = 20.', es:'"Boards" = los pasajeros suben al avión. Twelve = 12, twenty = 20.' },
      card:{ en:'Boarding gate', es:'Puerta de embarque' } },
    TEACH('travel'),
  ]},
  { distrito:'airport', orden:2, titulo:'Security check', tituloEs:'Control de seguridad', npc:'Officer Dan', npcIcon:'💂', pasos:[
    { type:'choice', say:'Please put your bag on the belt.', sayEs:'Por favor ponga su bolso en la banda.',
      opts:['Sure, no problem.','Sure, no trouble me.','I put not.','The bag no.'], answer:0,
      feedback:{ en:'"Sure, no problem" is a friendly way to say OK.', es:'"Sure, no problem" es una forma amable de decir OK.' },
      card:{ en:'Sure, no problem', es:'Claro, no hay problema' } },
    { type:'build', say:'Ask if you can keep your shoes on.', sayEs:'Pregunta si puedes dejarte los zapatos.',
      words:['keep','shoes','Can','my','I','on?'], answer:'Can I keep my shoes on',
      feedback:{ en:'"Can I...?" asks for permission.', es:'"Can I...?" pide permiso.' },
      card:{ en:'Can I keep... on?', es:'¿Puedo dejarme... puesto?' } },
    { type:'listen', say:'Take your laptop out of the bag.', sayEs:'Escucha la instrucción.',
      opts:['Take your laptop out of the bag.','Take your wallet out of the bag.','Put your laptop into the bag.'], answer:0,
      feedback:{ en:'"Take out" = remove. "Put into" = insert.', es:'"Take out" = sacar. "Put into" = meter.' },
      card:{ en:'Take out', es:'Sacar' } },
  ]},
  { distrito:'airport', orden:3, titulo:'Delayed flight', tituloEs:'Vuelo retrasado', npc:'Agent Maya', npcIcon:'👩‍✈️', pasos:[
    { type:'choice', say:'I am sorry, your flight is delayed.', sayEs:'Lo siento, su vuelo está retrasado.',
      opts:['How long is the delay?','How long the delay is?','How many is the delay?','When delay?'], answer:0,
      feedback:{ en:'Question order: How long + is + the delay?', es:'Orden de la pregunta: How long + is + the delay?' },
      card:{ en:'How long is the delay?', es:'¿De cuánto es el retraso?' } },
    { type:'build', say:'Ask where you can wait.', sayEs:'Pregunta dónde puedes esperar.',
      words:['can','Where','wait?','I'], answer:'Where can I wait',
      feedback:{ en:'Questions with can: Where + can + I + verb.', es:'Preguntas con can: Where + can + I + verbo.' },
      card:{ en:'Where can I wait?', es:'¿Dónde puedo esperar?' } },
    { type:'listen', say:'The new departure time is three thirty.', sayEs:'Escucha la nueva hora de salida.',
      opts:['The new departure time is three thirty.','The new departure time is three thirteen.','The new arrival time is three thirty.'], answer:0,
      feedback:{ en:'Thirty = 30, thirteen = 13. Departure = leaving, arrival = coming.', es:'Thirty = 30, thirteen = 13. Departure = salida, arrival = llegada.' },
      card:{ en:'Departure time', es:'Hora de salida' } },
    TEACH('an airport'),
  ]},

  // ═══════════ MALL — Shopping & comparatives ═══════════
  { distrito:'mall', orden:1, titulo:'The perfect T-shirt', tituloEs:'La camiseta perfecta', npc:'Clerk Ana', npcIcon:'🙋‍♀️', pasos:[
    { type:'choice', say:'Hi! Can I help you find something?', sayEs:'¡Hola! ¿Le ayudo a buscar algo?',
      opts:['Yes, I am looking for a T-shirt.','Yes, I look T-shirt.','Yes, T-shirt I see.','Yes, give T-shirt.'], answer:0,
      feedback:{ en:'"I am looking for..." = I want to find something.', es:'"I am looking for..." = quiero encontrar algo.' },
      card:{ en:'I am looking for...', es:'Estoy buscando...' } },
    { type:'build', say:'Compare the two T-shirts.', sayEs:'Compara las dos camisetas.',
      words:['than','blue','cheaper','the','is','one','The','red'], answer:'The blue one is cheaper than the red',
      feedback:{ en:'Short adjectives use -ER + than: cheap → cheaper than.', es:'Los adjetivos cortos usan -ER + than: cheap → cheaper than.' },
      card:{ en:'Cheaper than', es:'Más barato que' } },
    { type:'listen', say:'The fitting room is next to the exit.', sayEs:'Escucha dónde está el probador.',
      opts:['The fitting room is next to the exit.','The fitting room is next to the entrance.','The fitting room is far from the exit.'], answer:0,
      feedback:{ en:'"Next to" = beside. Exit = way out, entrance = way in.', es:'"Next to" = al lado de. Exit = salida, entrance = entrada.' },
      card:{ en:'Fitting room', es:'Probador' } },
    TEACH('shopping'),
  ]},
  { distrito:'mall', orden:2, titulo:'Which one is better?', tituloEs:'¿Cuál es mejor?', npc:'Clerk Ana', npcIcon:'🙋‍♀️', pasos:[
    { type:'choice', say:'These are our two most popular phones.', sayEs:'Estos son nuestros dos teléfonos más populares.',
      opts:['Which one is better?','Which one is more good?','Which one is gooder?','What one is best of two?'], answer:0,
      feedback:{ en:'"Good" is irregular: good → better → the best. Never "gooder".', es:'"Good" es irregular: good → better → the best. Nunca "gooder".' },
      card:{ en:'Better / The best', es:'Mejor / El mejor' } },
    { type:'build', say:'Say this phone is the most expensive.', sayEs:'Di que este teléfono es el más caro.',
      words:['most','This','the','phone','expensive','is'], answer:'This phone is the most expensive',
      feedback:{ en:'Long adjectives use "the most": the most expensive.', es:'Los adjetivos largos usan "the most": the most expensive.' },
      card:{ en:'The most expensive', es:'El más caro' } },
    { type:'listen', say:'It is on sale, twenty percent off.', sayEs:'Escucha la oferta.',
      opts:['It is on sale, twenty percent off.','It is on sale, twelve percent off.','It is not on sale this weekend.'], answer:0,
      feedback:{ en:'"On sale" = discount. "Percent off" = discount amount.', es:'"On sale" = en oferta. "Percent off" = porcentaje de descuento.' },
      card:{ en:'On sale', es:'En oferta' } },
  ]},
  { distrito:'mall', orden:3, titulo:'Returns & sizes', tituloEs:'Devoluciones y tallas', npc:'Manager Leo', npcIcon:'👨‍💼', pasos:[
    { type:'choice', say:'Is there a problem with your purchase?', sayEs:'¿Hay algún problema con su compra?',
      opts:['Yes, it is too small. Can I change it?','Yes, it is very small much.','Yes, small it is too.','Yes, it small.'], answer:0,
      feedback:{ en:'"Too + adjective" = more than you want: too small, too big.', es:'"Too + adjetivo" = más de lo que quieres: too small (demasiado pequeño).' },
      card:{ en:'Too small / Too big', es:'Demasiado pequeño / grande' } },
    { type:'build', say:'Ask for a bigger size.', sayEs:'Pide una talla más grande.',
      words:['a','size?','have','bigger','Do','you'], answer:'Do you have a bigger size',
      feedback:{ en:'"Do you have...?" asks if the store has something.', es:'"Do you have...?" pregunta si la tienda tiene algo.' },
      card:{ en:'Do you have a bigger size?', es:'¿Tiene una talla más grande?' } },
    { type:'listen', say:'You need the receipt to return it.', sayEs:'Escucha qué necesitas para devolverlo.',
      opts:['You need the receipt to return it.','You need the recipe to return it.','You need the ticket to buy it.'], answer:0,
      feedback:{ en:'Receipt = proof of purchase. Recipe = cooking instructions!', es:'Receipt = recibo de compra. Recipe = ¡receta de cocina!' },
      card:{ en:'Receipt', es:'Recibo / Factura' } },
    TEACH('the mall'),
  ]},

  // ═══════════ STATION — Directions (desbloqueo por equipo) ═══════════
  { distrito:'station', orden:1, titulo:'Lost in the city', tituloEs:'Perdido en la ciudad', npc:'Local Ben', npcIcon:'🧢', pasos:[
    { type:'choice', say:'You look lost! Can I help?', sayEs:'¡Te ves perdido! ¿Te ayudo?',
      opts:['Yes! How do I get to the station?','Yes! How I get station?','Yes! Where station going?','Yes! Station where is go?'], answer:0,
      feedback:{ en:'"How do I get to...?" is THE question for directions.', es:'"How do I get to...?" es LA pregunta para pedir direcciones.' },
      card:{ en:'How do I get to...?', es:'¿Cómo llego a...?' } },
    { type:'build', say:'Give directions: first right, then straight.', sayEs:'Da direcciones: primera a la derecha, luego derecho.',
      words:['right','go','Turn','then','straight'], answer:'Turn right then go straight',
      feedback:{ en:'Directions use imperatives: Turn right. Go straight. No subject.', es:'Las direcciones usan imperativo: Turn right. Go straight. Sin sujeto.' },
      card:{ en:'Turn right / Go straight', es:'Gira a la derecha / Sigue derecho' } },
    { type:'listen', say:'The station is across from the bank.', sayEs:'Escucha dónde está la estación.',
      opts:['The station is across from the bank.','The station is behind the bank.','The station is inside the bank.'], answer:0,
      feedback:{ en:'"Across from" = on the other side of the street.', es:'"Across from" = al otro lado de la calle.' },
      card:{ en:'Across from', es:'Frente a / Al otro lado de' } },
    TEACH('directions'),
  ]},
  { distrito:'station', orden:2, titulo:'Buying a ticket', tituloEs:'Comprando un tiquete', npc:'Cashier Kim', npcIcon:'👩‍💼', pasos:[
    { type:'choice', say:'Where to?', sayEs:'¿Hacia dónde?',
      opts:['A round-trip ticket to Green Park, please.','A ticket go and come Green Park.','Ticket two ways Green Park.','Green Park ticket you give.'], answer:0,
      feedback:{ en:'"Round-trip" = go AND come back. "One-way" = only go.', es:'"Round-trip" = ida y vuelta. "One-way" = solo ida.' },
      card:{ en:'Round-trip ticket', es:'Tiquete ida y vuelta' } },
    { type:'build', say:'Ask which platform.', sayEs:'Pregunta cuál andén.',
      words:['platform','leave','does','from?','it','Which'], answer:'Which platform does it leave from',
      feedback:{ en:'"Which platform does it leave from?" — questions with does.', es:'"Which platform does it leave from?" — preguntas con does.' },
      card:{ en:'Which platform?', es:'¿Cuál andén?' } },
    { type:'listen', say:'The next train leaves in ten minutes.', sayEs:'Escucha cuándo sale el próximo tren.',
      opts:['The next train leaves in ten minutes.','The next train leaves in ten hours.','The last train left ten minutes ago.'], answer:0,
      feedback:{ en:'"In ten minutes" = 10 minutes from now.', es:'"In ten minutes" = dentro de 10 minutos.' },
      card:{ en:'It leaves in...', es:'Sale en...' } },
  ]},
  { distrito:'station', orden:3, titulo:'The wrong bus', tituloEs:'El bus equivocado', npc:'Driver Ray', npcIcon:'🚌', pasos:[
    { type:'choice', say:'This bus goes downtown. Where are you going?', sayEs:'Este bus va al centro. ¿A dónde vas?',
      opts:['Oh no, I took the wrong bus!','Oh no, I take bus wrong!','Oh no, wrong bus take me!','Oh no, bus is wrong of me!'], answer:0,
      feedback:{ en:'Past of take = took. "I took the wrong bus."', es:'El pasado de take = took. "I took the wrong bus."' },
      card:{ en:'I took the wrong bus', es:'Tomé el bus equivocado' } },
    { type:'build', say:'Ask where to get off.', sayEs:'Pregunta dónde bajarte.',
      words:['I','off?','should','get','Where'], answer:'Where should I get off',
      feedback:{ en:'"Get off" = exit the bus. "Get on" = enter the bus.', es:'"Get off" = bajarse. "Get on" = subirse.' },
      card:{ en:'Get off / Get on', es:'Bajarse / Subirse' } },
    { type:'listen', say:'Get off at the third stop.', sayEs:'Escucha en qué parada bajarte.',
      opts:['Get off at the third stop.','Get off at the first stop.','Get on at the third stop.'], answer:0,
      feedback:{ en:'Third = 3rd. Ordinals: first, second, third.', es:'Third = tercera. Ordinales: first, second, third.' },
      card:{ en:'The third stop', es:'La tercera parada' } },
    TEACH('the city'),
  ]},

  // ═══════════ HOSPITAL — Health (desbloqueo por equipo) ═══════════
  { distrito:'hospital', orden:1, titulo:'At the doctor', tituloEs:'En el médico', npc:'Dr. Reyes', npcIcon:'🧑‍⚕️', pasos:[
    { type:'choice', say:'Good morning. What seems to be the problem?', sayEs:'Buenos días. ¿Cuál parece ser el problema?',
      opts:['I have a headache and a fever.','I am a headache and fever.','My head is ache and fever me.','Headache me and fever.'], answer:0,
      feedback:{ en:'"I HAVE a headache" — symptoms use have, not am.', es:'"I HAVE a headache" — los síntomas usan have, no am.' },
      card:{ en:'I have a headache', es:'Tengo dolor de cabeza' } },
    { type:'build', say:'Say how long you have felt sick.', sayEs:'Di hace cuánto te sientes mal.',
      words:['sick','for','been','have','days','I','two'], answer:'I have been sick for two days',
      feedback:{ en:'"I have been sick FOR two days" — for + period of time.', es:'"I have been sick FOR two days" — for + periodo de tiempo.' },
      card:{ en:'For two days', es:'Desde hace dos días' } },
    { type:'listen', say:'Take this medicine twice a day.', sayEs:'Escucha las instrucciones del doctor.',
      opts:['Take this medicine twice a day.','Take this medicine two in a day.','Take this medicine every two days.'], answer:0,
      feedback:{ en:'"Twice a day" = two times per day.', es:'"Twice a day" = dos veces al día.' },
      card:{ en:'Twice a day', es:'Dos veces al día' } },
    TEACH('health'),
  ]},
  { distrito:'hospital', orden:2, titulo:'The pharmacy', tituloEs:'La farmacia', npc:'Pharmacist Ivy', npcIcon:'💊', pasos:[
    { type:'choice', say:'Do you have a prescription?', sayEs:'¿Tiene una receta médica?',
      opts:['Yes, here it is.','Yes, here is she.','Yes, this is here.','Yes, it here are.'], answer:0,
      feedback:{ en:'"Here it is" — when you hand over ONE thing.', es:'"Here it is" — cuando entregas UNA cosa.' },
      card:{ en:'Here it is', es:'Aquí está' } },
    { type:'build', say:'Ask about side effects.', sayEs:'Pregunta por los efectos secundarios.',
      words:['side','have','it','effects?','Does','any'], answer:'Does it have any side effects',
      feedback:{ en:'Questions with does: Does + it + verb...?', es:'Preguntas con does: Does + it + verbo...?' },
      card:{ en:'Side effects', es:'Efectos secundarios' } },
    { type:'listen', say:'Do not take it on an empty stomach.', sayEs:'Escucha la advertencia.',
      opts:['Do not take it on an empty stomach.','Do not take it on a full stomach.','Take it on an empty stomach.'], answer:0,
      feedback:{ en:'"On an empty stomach" = without eating first.', es:'"On an empty stomach" = con el estómago vacío.' },
      card:{ en:'On an empty stomach', es:'Con el estómago vacío' } },
  ]},
  { distrito:'hospital', orden:3, titulo:'Emergency!', tituloEs:'¡Emergencia!', npc:'Nurse Omar', npcIcon:'🚑', pasos:[
    { type:'choice', say:'Emergency room, how can I help?', sayEs:'Sala de emergencias, ¿cómo puedo ayudar?',
      opts:['My friend hurt his leg!','My friend is hurt of leg!','The leg of my friend hurting!','Friend leg hurt very!'], answer:0,
      feedback:{ en:'Past of hurt = hurt (no change): "He hurt his leg."', es:'El pasado de hurt = hurt (no cambia): "He hurt his leg."' },
      card:{ en:'He hurt his leg', es:'Se lastimó la pierna' } },
    { type:'build', say:'Say it hurts a lot.', sayEs:'Di que duele mucho.',
      words:['lot','hurts','It','a'], answer:'It hurts a lot',
      feedback:{ en:'"It hurts" — the body part is the subject: My leg hurts.', es:'"It hurts" — la parte del cuerpo es el sujeto: My leg hurts.' },
      card:{ en:'It hurts a lot', es:'Duele mucho' } },
    { type:'listen', say:'The doctor will see you right away.', sayEs:'Escucha a la enfermera.',
      opts:['The doctor will see you right away.','The doctor will see you next Friday.','The doctor saw you yesterday.'], answer:0,
      feedback:{ en:'"Right away" = immediately, now.', es:'"Right away" = de inmediato, ya.' },
      card:{ en:'Right away', es:'De inmediato' } },
    TEACH('a hospital'),
  ]},

  // ═══════════ NEIGHBORHOOD — Past simple (desbloqueo por equipo) ═══════════
  { distrito:'neighborhood', orden:1, titulo:'What did you do yesterday?', tituloEs:'¿Qué hiciste ayer?', npc:'Neighbor Rosa', npcIcon:'👵', pasos:[
    { type:'choice', say:'Hi! I did not see you yesterday. What did you do?', sayEs:'¡Hola! No te vi ayer. ¿Qué hiciste?',
      opts:['I visited my grandmother.','I visit my grandmother yesterday.','I am visit my grandmother.','I visiting my grandmother.'], answer:0,
      feedback:{ en:'Past simple: regular verbs add -ED. Visit → visited.', es:'Pasado simple: los verbos regulares agregan -ED. Visit → visited.' },
      card:{ en:'I visited...', es:'Visité...' } },
    { type:'build', say:'Say you went to the park.', sayEs:'Di que fuiste al parque.',
      words:['park','the','to','went','I'], answer:'I went to the park',
      feedback:{ en:'Go is irregular: go → went. Never "goed".', es:'Go es irregular: go → went. Nunca "goed".' },
      card:{ en:'I went to...', es:'Fui a...' } },
    { type:'listen', say:'We had a barbecue last Sunday.', sayEs:'Escucha qué hizo Rosa.',
      opts:['We had a barbecue last Sunday.','We have a barbecue this Sunday.','We had a birthday last Sunday.'], answer:0,
      feedback:{ en:'Have is irregular: have → had. "Last Sunday" = past.', es:'Have es irregular: have → had. "Last Sunday" = pasado.' },
      card:{ en:'Last Sunday', es:'El domingo pasado' } },
    TEACH('yesterday'),
  ]},
  { distrito:'neighborhood', orden:2, titulo:'The lost cat', tituloEs:'El gato perdido', npc:'Kid Tommy', npcIcon:'🧒', pasos:[
    { type:'choice', say:'Did you see my cat? He escaped this morning!', sayEs:'¿Viste a mi gato? ¡Se escapó esta mañana!',
      opts:['Yes! I saw him near the store.','Yes! I see him near the store.','Yes! I seen him near the store.','Yes! I was see him.'], answer:0,
      feedback:{ en:'See is irregular: see → saw. "I saw him" for past.', es:'See es irregular: see → saw. "I saw him" para pasado.' },
      card:{ en:'I saw him', es:'Lo vi' } },
    { type:'build', say:'Ask when he escaped.', sayEs:'Pregunta cuándo se escapó.',
      words:['escape?','time','did','What','he'], answer:'What time did he escape',
      feedback:{ en:'Past questions: did + base verb. NOT "did escaped".', es:'Preguntas en pasado: did + verbo base. NO "did escaped".' },
      card:{ en:'What time did...?', es:'¿A qué hora...?' } },
    { type:'listen', say:'He ran into the garden next door.', sayEs:'Escucha a dónde corrió el gato.',
      opts:['He ran into the garden next door.','He runs into the garden every day.','He ran into the kitchen next door.'], answer:0,
      feedback:{ en:'Run is irregular: run → ran. "Next door" = the house beside yours.', es:'Run es irregular: run → ran. "Next door" = la casa de al lado.' },
      card:{ en:'Next door', es:'La casa de al lado' } },
  ]},
  { distrito:'neighborhood', orden:3, titulo:'The block party', tituloEs:'La fiesta del barrio', npc:'Neighbor Rosa', npcIcon:'👵', pasos:[
    { type:'choice', say:'The party was amazing! Why did you not come?', sayEs:'¡La fiesta estuvo increíble! ¿Por qué no viniste?',
      opts:['I could not come because I worked late.','I no can come because work late.','I did not can come, work late.','Because worked late I not come.'], answer:0,
      feedback:{ en:'Past of can = could. "I could not come."', es:'El pasado de can = could. "I could not come."' },
      card:{ en:'I could not come', es:'No pude venir' } },
    { type:'build', say:'Ask what they ate.', sayEs:'Pregunta qué comieron.',
      words:['you','What','eat?','did'], answer:'What did you eat',
      feedback:{ en:'Past questions: What + did + you + base verb.', es:'Preguntas en pasado: What + did + you + verbo base.' },
      card:{ en:'What did you eat?', es:'¿Qué comieron?' } },
    { type:'listen', say:'Everybody danced until midnight.', sayEs:'Escucha hasta qué hora bailaron.',
      opts:['Everybody danced until midnight.','Everybody dances at midnight.','Everybody danced after midnight.'], answer:0,
      feedback:{ en:'"Until midnight" = up to 12:00 AM, then stopped.', es:'"Until midnight" = hasta la medianoche, luego pararon.' },
      card:{ en:'Until midnight', es:'Hasta la medianoche' } },
    TEACH('a party'),
  ]},
];

async function seed() {
  await CityDistrict.deleteMany({});
  await CityMission.deleteMany({});
  await CityDistrict.insertMany(DISTRITOS);
  await CityMission.insertMany(MISIONES);
  const pasos = MISIONES.reduce((a, m) => a + m.pasos.length, 0);
  console.log(`✅ City: ${DISTRITOS.length} distritos y ${MISIONES.length} misiones (${pasos} pasos) insertados`);
  mongoose.disconnect();
}
